### PR TITLE
Fix memleaks in work with struct types

### LINKED ISSUE #1879: Mem leaks
We still have quite a few memleaks when building with LLVM12  &  libbpf:

```
sudo ./src/bpftrace /vagrant/tools/tcplife.bt
Attaching 3 probes...
PID   COMM       LADDR           LPORT RADDR           RPORT TX_KB RX_KB MS

=================================================================
==1518528==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 1561896 byte(s) in 549 object(s) allocated from:
    #0 0x7fa1773ce5a7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x555a2d856a17 in __gnu_cxx::new_allocator<bpftrace::Field>::allocate(unsigned long, void const*) /usr/include/c++/10/ext/new_allocator.h:115
    #2 0x555a2d8544e8 in std::allocator_traits<std::allocator<bpftrace::Field> >::allocate(std::allocator<bpftrace::Field>&, unsigned long) /usr/include/c++/10/bits/alloc_traits.h:460
    #3 0x555a2d850c85 in std::_Vector_base<bpftrace::Field, std::allocator<bpftrace::Field> >::_M_allocate(unsigned long) /usr/include/c++/10/bits/stl_vector.h:346
    #4 0x555a2d8ac102 in void std::vector<bpftrace::Field, std::allocator<bpftrace::Field> >::_M_realloc_insert<bpftrace::Field>(__gnu_cxx::__normal_iterator<bpftrace::Field*, std::vector<bpftrace::Field, std::allocator<bpftrace::Field> > >, bpftrace::Field&&) /usr/include/c++/10/bits/vector.tcc:440
    #5 0x555a2d8abb56 in bpftrace::Field& std::vector<bpftrace::Field, std::allocator<bpftrace::Field> >::emplace_back<bpftrace::Field>(bpftrace::Field&&) /usr/include/c++/10/bits/vector.tcc:121
    #6 0x555a2d8aa623 in bpftrace::Struct::AddField(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bpftrace::SizedType const&, long, bool, bpftrace::Bitfield const&, bool) /vagrant/src/struct.cpp:113
    #7 0x555a2d86ad19 in operator() /vagrant/src/clang_parser.cpp:572
    #8 0x555a2d86ae9d in _FUN /vagrant/src/clang_parser.cpp:577
    #9 0x7fa175ea36f1  (/usr/lib/llvm-12/lib/libclang-12.so.1+0x4456f1)

Indirect leak of 282264 byte(s) in 1857 object(s) allocated from:
    #0 0x7fa1773ce5a7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x555a2d8bc11d in __gnu_cxx::new_allocator<std::_Sp_counted_ptr_inplace<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, (__gnu_cxx::_Lock_policy)2> >::allocate(unsigned long, void const*) /usr/include/c++/10/ext/new_allocator.h:115
    #2 0x555a2d8bbf16 in std::allocator_traits<std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, (__gnu_cxx::_Lock_policy)2> > >::allocate(std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, (__gnu_cxx::_Lock_policy)2> >&, unsigned long) /usr/include/c++/10/bits/alloc_traits.h:460
    #3 0x555a2d8bbb89 in std::__allocated_ptr<std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, (__gnu_cxx::_Lock_policy)2> > > std::__allocate_guarded<std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, (__gnu_cxx::_Lock_policy)2> > >(std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, (__gnu_cxx::_Lock_policy)2> >&) /usr/include/c++/10/bits/allocated_ptr.h:97
    #4 0x555a2d8bb90b in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, bpftrace::SizedType const&>(bpftrace::SizedType*&, std::_Sp_alloc_shared_tag<std::allocator<bpftrace::SizedType> >, bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr_base.h:680
    #5 0x555a2d8bb78f in std::__shared_ptr<bpftrace::SizedType, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<bpftrace::SizedType>, bpftrace::SizedType const&>(std::_Sp_alloc_shared_tag<std::allocator<bpftrace::SizedType> >, bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr_base.h:1371
    #6 0x555a2d8bb5f4 in std::shared_ptr<bpftrace::SizedType>::shared_ptr<std::allocator<bpftrace::SizedType>, bpftrace::SizedType const&>(std::_Sp_alloc_shared_tag<std::allocator<bpftrace::SizedType> >, bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr.h:408
    #7 0x555a2d8bb519 in std::shared_ptr<bpftrace::SizedType> std::allocate_shared<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, bpftrace::SizedType const&>(std::allocator<bpftrace::SizedType> const&, bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr.h:860
    #8 0x555a2d8bb43d in std::shared_ptr<bpftrace::SizedType> std::make_shared<bpftrace::SizedType, bpftrace::SizedType const&>(bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr.h:876
    #9 0x555a2d8b70f7 in bpftrace::CreatePointer(bpftrace::SizedType const&, bpftrace::AddrSpace) /vagrant/src/types.cpp:354
    #10 0x555a2d869aec in get_sized_type /vagrant/src/clang_parser.cpp:328
    #11 0x555a2d86abad in operator() /vagrant/src/clang_parser.cpp:543
    #12 0x555a2d86ae9d in _FUN /vagrant/src/clang_parser.cpp:577
    #13 0x7fa175ea36f1  (/usr/lib/llvm-12/lib/libclang-12.so.1+0x4456f1)

Indirect leak of 29488 byte(s) in 194 object(s) allocated from:
    #0 0x7fa1773ce5a7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x555a2d8bc11d in __gnu_cxx::new_allocator<std::_Sp_counted_ptr_inplace<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, (__gnu_cxx::_Lock_policy)2> >::allocate(unsigned long, void const*) /usr/include/c++/10/ext/new_allocator.h:115
    #2 0x555a2d8bbf16 in std::allocator_traits<std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, (__gnu_cxx::_Lock_policy)2> > >::allocate(std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, (__gnu_cxx::_Lock_policy)2> >&, unsigned long) /usr/include/c++/10/bits/alloc_traits.h:460
    #3 0x555a2d8bbb89 in std::__allocated_ptr<std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, (__gnu_cxx::_Lock_policy)2> > > std::__allocate_guarded<std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, (__gnu_cxx::_Lock_policy)2> > >(std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, (__gnu_cxx::_Lock_policy)2> >&) /usr/include/c++/10/bits/allocated_ptr.h:97
    #4 0x555a2d8bb90b in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, bpftrace::SizedType const&>(bpftrace::SizedType*&, std::_Sp_alloc_shared_tag<std::allocator<bpftrace::SizedType> >, bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr_base.h:680
    #5 0x555a2d8bb78f in std::__shared_ptr<bpftrace::SizedType, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<bpftrace::SizedType>, bpftrace::SizedType const&>(std::_Sp_alloc_shared_tag<std::allocator<bpftrace::SizedType> >, bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr_base.h:1371
    #6 0x555a2d8bb5f4 in std::shared_ptr<bpftrace::SizedType>::shared_ptr<std::allocator<bpftrace::SizedType>, bpftrace::SizedType const&>(std::_Sp_alloc_shared_tag<std::allocator<bpftrace::SizedType> >, bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr.h:408
    #7 0x555a2d8bb519 in std::shared_ptr<bpftrace::SizedType> std::allocate_shared<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, bpftrace::SizedType const&>(std::allocator<bpftrace::SizedType> const&, bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr.h:860
    #8 0x555a2d8bb43d in std::shared_ptr<bpftrace::SizedType> std::make_shared<bpftrace::SizedType, bpftrace::SizedType const&>(bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr.h:876
    #9 0x555a2d8b7045 in bpftrace::CreateArray(unsigned long, bpftrace::SizedType const&) /vagrant/src/types.cpp:346
    #10 0x555a2d869bc2 in get_sized_type /vagrant/src/clang_parser.cpp:340
    #11 0x555a2d86abad in operator() /vagrant/src/clang_parser.cpp:543
    #12 0x555a2d86ae9d in _FUN /vagrant/src/clang_parser.cpp:577
    #13 0x7fa175ea36f1  (/usr/lib/llvm-12/lib/libclang-12.so.1+0x4456f1)

Indirect leak of 23464 byte(s) in 419 object(s) allocated from:
    #0 0x7fa1773ce5a7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x555a2d8ae969 in __gnu_cxx::new_allocator<std::_Sp_counted_ptr_inplace<bpftrace::Struct, std::allocator<bpftrace::Struct>, (__gnu_cxx::_Lock_policy)2> >::allocate(unsigned long, void const*) /usr/include/c++/10/ext/new_allocator.h:115
    #2 0x555a2d8ae76e in std::allocator_traits<std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::Struct, std::allocator<bpftrace::Struct>, (__gnu_cxx::_Lock_policy)2> > >::allocate(std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::Struct, std::allocator<bpftrace::Struct>, (__gnu_cxx::_Lock_policy)2> >&, unsigned long) /usr/include/c++/10/bits/alloc_traits.h:460
    #3 0x555a2d8ae389 in std::__allocated_ptr<std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::Struct, std::allocator<bpftrace::Struct>, (__gnu_cxx::_Lock_policy)2> > > std::__allocate_guarded<std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::Struct, std::allocator<bpftrace::Struct>, (__gnu_cxx::_Lock_policy)2> > >(std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::Struct, std::allocator<bpftrace::Struct>, (__gnu_cxx::_Lock_policy)2> >&) /usr/include/c++/10/bits/allocated_ptr.h:97
    #4 0x555a2d8adf99 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<bpftrace::Struct, std::allocator<bpftrace::Struct>, unsigned long&>(bpftrace::Struct*&, std::_Sp_alloc_shared_tag<std::allocator<bpftrace::Struct> >, unsigned long&) /usr/include/c++/10/bits/shared_ptr_base.h:680
    #5 0x555a2d8adc0b in std::__shared_ptr<bpftrace::Struct, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<bpftrace::Struct>, unsigned long&>(std::_Sp_alloc_shared_tag<std::allocator<bpftrace::Struct> >, unsigned long&) /usr/include/c++/10/bits/shared_ptr_base.h:1371
    #6 0x555a2d8ad3ea in std::shared_ptr<bpftrace::Struct>::shared_ptr<std::allocator<bpftrace::Struct>, unsigned long&>(std::_Sp_alloc_shared_tag<std::allocator<bpftrace::Struct> >, unsigned long&) /usr/include/c++/10/bits/shared_ptr.h:408
    #7 0x555a2d8ac66a in std::shared_ptr<bpftrace::Struct> std::allocate_shared<bpftrace::Struct, std::allocator<bpftrace::Struct>, unsigned long&>(std::allocator<bpftrace::Struct> const&, unsigned long&) /usr/include/c++/10/bits/shared_ptr.h:860
    #8 0x555a2d8abd4c in std::shared_ptr<bpftrace::Struct> std::make_shared<bpftrace::Struct, unsigned long&>(unsigned long&) /usr/include/c++/10/bits/shared_ptr.h:876
    #9 0x555a2d8aa789 in bpftrace::StructManager::Add(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long) /vagrant/src/struct.cpp:121
    #10 0x555a2d86acaf in operator() /vagrant/src/clang_parser.cpp:567
    #11 0x555a2d86ae9d in _FUN /vagrant/src/clang_parser.cpp:577
    #12 0x7fa175ea36f1  (/usr/lib/llvm-12/lib/libclang-12.so.1+0x4456f1)

Indirect leak of 16780 byte(s) in 721 object(s) allocated from:
    #0 0x7fa1773ce5a7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x555a2d7aa659 in void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*>(char*, char*, std::forward_iterator_tag) (/home/vagrant/build-asan/src/bpftrace+0xde659)
    #2 0x555a2d83fe98 in bpftrace::SizedType::SizedType(bpftrace::SizedType const&) (/home/vagrant/build-asan/src/bpftrace+0x173e98)
    #3 0x555a2d8aa5d4 in bpftrace::Struct::AddField(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bpftrace::SizedType const&, long, bool, bpftrace::Bitfield const&, bool) /vagrant/src/struct.cpp:108
    #4 0x555a2d86ad19 in operator() /vagrant/src/clang_parser.cpp:572
    #5 0x555a2d86ae9d in _FUN /vagrant/src/clang_parser.cpp:577
    #6 0x7fa175ea36f1  (/usr/lib/llvm-12/lib/libclang-12.so.1+0x4456f1)

Indirect leak of 16464 byte(s) in 294 object(s) allocated from:
    #0 0x7fa1773ce5a7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x555a2d8ae969 in __gnu_cxx::new_allocator<std::_Sp_counted_ptr_inplace<bpftrace::Struct, std::allocator<bpftrace::Struct>, (__gnu_cxx::_Lock_policy)2> >::allocate(unsigned long, void const*) /usr/include/c++/10/ext/new_allocator.h:115
    #2 0x555a2d8ae76e in std::allocator_traits<std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::Struct, std::allocator<bpftrace::Struct>, (__gnu_cxx::_Lock_policy)2> > >::allocate(std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::Struct, std::allocator<bpftrace::Struct>, (__gnu_cxx::_Lock_policy)2> >&, unsigned long) /usr/include/c++/10/bits/alloc_traits.h:460
    #3 0x555a2d8ae389 in std::__allocated_ptr<std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::Struct, std::allocator<bpftrace::Struct>, (__gnu_cxx::_Lock_policy)2> > > std::__allocate_guarded<std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::Struct, std::allocator<bpftrace::Struct>, (__gnu_cxx::_Lock_policy)2> > >(std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::Struct, std::allocator<bpftrace::Struct>, (__gnu_cxx::_Lock_policy)2> >&) /usr/include/c++/10/bits/allocated_ptr.h:97
    #4 0x555a2d8adf99 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<bpftrace::Struct, std::allocator<bpftrace::Struct>, unsigned long&>(bpftrace::Struct*&, std::_Sp_alloc_shared_tag<std::allocator<bpftrace::Struct> >, unsigned long&) /usr/include/c++/10/bits/shared_ptr_base.h:680
    #5 0x555a2d8adc0b in std::__shared_ptr<bpftrace::Struct, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<bpftrace::Struct>, unsigned long&>(std::_Sp_alloc_shared_tag<std::allocator<bpftrace::Struct> >, unsigned long&) /usr/include/c++/10/bits/shared_ptr_base.h:1371
    #6 0x555a2d8ad3ea in std::shared_ptr<bpftrace::Struct>::shared_ptr<std::allocator<bpftrace::Struct>, unsigned long&>(std::_Sp_alloc_shared_tag<std::allocator<bpftrace::Struct> >, unsigned long&) /usr/include/c++/10/bits/shared_ptr.h:408
    #7 0x555a2d8ac66a in std::shared_ptr<bpftrace::Struct> std::allocate_shared<bpftrace::Struct, std::allocator<bpftrace::Struct>, unsigned long&>(std::allocator<bpftrace::Struct> const&, unsigned long&) /usr/include/c++/10/bits/shared_ptr.h:860
    #8 0x555a2d8abd4c in std::shared_ptr<bpftrace::Struct> std::make_shared<bpftrace::Struct, unsigned long&>(unsigned long&) /usr/include/c++/10/bits/shared_ptr.h:876
    #9 0x555a2d8aa946 in bpftrace::StructManager::LookupOrAdd(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long) /vagrant/src/struct.cpp:133
    #10 0x555a2d8699e3 in get_sized_type /vagrant/src/clang_parser.cpp:313
    #11 0x555a2d869aca in get_sized_type /vagrant/src/clang_parser.cpp:328
    #12 0x555a2d86abad in operator() /vagrant/src/clang_parser.cpp:543
    #13 0x555a2d86ae9d in _FUN /vagrant/src/clang_parser.cpp:577
    #14 0x7fa175ea36f1  (/usr/lib/llvm-12/lib/libclang-12.so.1+0x4456f1)

Indirect leak of 14521 byte(s) in 713 object(s) allocated from:
    #0 0x7fa1773ce5a7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x555a2d7aa659 in void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*>(char*, char*, std::forward_iterator_tag) (/home/vagrant/build-asan/src/bpftrace+0xde659)
    #2 0x555a2d8aa5b7 in bpftrace::Struct::AddField(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bpftrace::SizedType const&, long, bool, bpftrace::Bitfield const&, bool) /vagrant/src/struct.cpp:108
    #3 0x555a2d86ad19 in operator() /vagrant/src/clang_parser.cpp:572
    #4 0x555a2d86ae9d in _FUN /vagrant/src/clang_parser.cpp:577
    #5 0x7fa175ea36f1  (/usr/lib/llvm-12/lib/libclang-12.so.1+0x4456f1)

Indirect leak of 12762 byte(s) in 603 object(s) allocated from:
    #0 0x7fa1773ce5a7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x555a2d7aa659 in void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*>(char*, char*, std::forward_iterator_tag) (/home/vagrant/build-asan/src/bpftrace+0xde659)
    #2 0x555a2d83fe98 in bpftrace::SizedType::SizedType(bpftrace::SizedType const&) (/home/vagrant/build-asan/src/bpftrace+0x173e98)
    #3 0x555a2d8bc1ec in void __gnu_cxx::new_allocator<bpftrace::SizedType>::construct<bpftrace::SizedType, bpftrace::SizedType const&>(bpftrace::SizedType*, bpftrace::SizedType const&) /usr/include/c++/10/ext/new_allocator.h:150
    #4 0x555a2d8bbffb in void std::allocator_traits<std::allocator<bpftrace::SizedType> >::construct<bpftrace::SizedType, bpftrace::SizedType const&>(std::allocator<bpftrace::SizedType>&, bpftrace::SizedType*, bpftrace::SizedType const&) /usr/include/c++/10/bits/alloc_traits.h:512
    #5 0x555a2d8bbcef in std::_Sp_counted_ptr_inplace<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<bpftrace::SizedType const&>(std::allocator<bpftrace::SizedType>, bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr_base.h:551
    #6 0x555a2d8bb963 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, bpftrace::SizedType const&>(bpftrace::SizedType*&, std::_Sp_alloc_shared_tag<std::allocator<bpftrace::SizedType> >, bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr_base.h:682
    #7 0x555a2d8bb78f in std::__shared_ptr<bpftrace::SizedType, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<bpftrace::SizedType>, bpftrace::SizedType const&>(std::_Sp_alloc_shared_tag<std::allocator<bpftrace::SizedType> >, bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr_base.h:1371
    #8 0x555a2d8bb5f4 in std::shared_ptr<bpftrace::SizedType>::shared_ptr<std::allocator<bpftrace::SizedType>, bpftrace::SizedType const&>(std::_Sp_alloc_shared_tag<std::allocator<bpftrace::SizedType> >, bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr.h:408
    #9 0x555a2d8bb519 in std::shared_ptr<bpftrace::SizedType> std::allocate_shared<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, bpftrace::SizedType const&>(std::allocator<bpftrace::SizedType> const&, bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr.h:860
    #10 0x555a2d8bb43d in std::shared_ptr<bpftrace::SizedType> std::make_shared<bpftrace::SizedType, bpftrace::SizedType const&>(bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr.h:876
    #11 0x555a2d8b70f7 in bpftrace::CreatePointer(bpftrace::SizedType const&, bpftrace::AddrSpace) /vagrant/src/types.cpp:354
    #12 0x555a2d869aec in get_sized_type /vagrant/src/clang_parser.cpp:328
    #13 0x555a2d86abad in operator() /vagrant/src/clang_parser.cpp:543
    #14 0x555a2d86ae9d in _FUN /vagrant/src/clang_parser.cpp:577
    #15 0x7fa175ea36f1  (/usr/lib/llvm-12/lib/libclang-12.so.1+0x4456f1)

Indirect leak of 5168 byte(s) in 34 object(s) allocated from:
    #0 0x7fa1773ce5a7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x555a2d8bc11d in __gnu_cxx::new_allocator<std::_Sp_counted_ptr_inplace<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, (__gnu_cxx::_Lock_policy)2> >::allocate(unsigned long, void const*) /usr/include/c++/10/ext/new_allocator.h:115
    #2 0x555a2d8bbf16 in std::allocator_traits<std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, (__gnu_cxx::_Lock_policy)2> > >::allocate(std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, (__gnu_cxx::_Lock_policy)2> >&, unsigned long) /usr/include/c++/10/bits/alloc_traits.h:460
    #3 0x555a2d8bbb89 in std::__allocated_ptr<std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, (__gnu_cxx::_Lock_policy)2> > > std::__allocate_guarded<std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, (__gnu_cxx::_Lock_policy)2> > >(std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, (__gnu_cxx::_Lock_policy)2> >&) /usr/include/c++/10/bits/allocated_ptr.h:97
    #4 0x555a2d8bb90b in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, bpftrace::SizedType const&>(bpftrace::SizedType*&, std::_Sp_alloc_shared_tag<std::allocator<bpftrace::SizedType> >, bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr_base.h:680
    #5 0x555a2d8bb78f in std::__shared_ptr<bpftrace::SizedType, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<bpftrace::SizedType>, bpftrace::SizedType const&>(std::_Sp_alloc_shared_tag<std::allocator<bpftrace::SizedType> >, bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr_base.h:1371
    #6 0x555a2d8bb5f4 in std::shared_ptr<bpftrace::SizedType>::shared_ptr<std::allocator<bpftrace::SizedType>, bpftrace::SizedType const&>(std::_Sp_alloc_shared_tag<std::allocator<bpftrace::SizedType> >, bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr.h:408
    #7 0x555a2d8bb519 in std::shared_ptr<bpftrace::SizedType> std::allocate_shared<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, bpftrace::SizedType const&>(std::allocator<bpftrace::SizedType> const&, bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr.h:860
    #8 0x555a2d8bb43d in std::shared_ptr<bpftrace::SizedType> std::make_shared<bpftrace::SizedType, bpftrace::SizedType const&>(bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr.h:876
    #9 0x555a2d8b70f7 in bpftrace::CreatePointer(bpftrace::SizedType const&, bpftrace::AddrSpace) /vagrant/src/types.cpp:354
    #10 0x555a2d869aec in get_sized_type /vagrant/src/clang_parser.cpp:328
    #11 0x555a2d869aca in get_sized_type /vagrant/src/clang_parser.cpp:328
    #12 0x555a2d86abad in operator() /vagrant/src/clang_parser.cpp:543
    #13 0x555a2d86ae9d in _FUN /vagrant/src/clang_parser.cpp:577
    #14 0x7fa175ea36f1  (/usr/lib/llvm-12/lib/libclang-12.so.1+0x4456f1)

Indirect leak of 5120 byte(s) in 1 object(s) allocated from:
    #0 0x7fa1773ce5a7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x7fa1723fb82e  (/usr/lib/llvm-12/lib/libLLVM-12.so.1+0x219782e)

Indirect leak of 4256 byte(s) in 28 object(s) allocated from:
    #0 0x7fa1773ce5a7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x555a2d8bc11d in __gnu_cxx::new_allocator<std::_Sp_counted_ptr_inplace<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, (__gnu_cxx::_Lock_policy)2> >::allocate(unsigned long, void const*) /usr/include/c++/10/ext/new_allocator.h:115
    #2 0x555a2d8bbf16 in std::allocator_traits<std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, (__gnu_cxx::_Lock_policy)2> > >::allocate(std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, (__gnu_cxx::_Lock_policy)2> >&, unsigned long) /usr/include/c++/10/bits/alloc_traits.h:460
    #3 0x555a2d8bbb89 in std::__allocated_ptr<std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, (__gnu_cxx::_Lock_policy)2> > > std::__allocate_guarded<std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, (__gnu_cxx::_Lock_policy)2> > >(std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, (__gnu_cxx::_Lock_policy)2> >&) /usr/include/c++/10/bits/allocated_ptr.h:97
    #4 0x555a2d8bb90b in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, bpftrace::SizedType const&>(bpftrace::SizedType*&, std::_Sp_alloc_shared_tag<std::allocator<bpftrace::SizedType> >, bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr_base.h:680
    #5 0x555a2d8bb78f in std::__shared_ptr<bpftrace::SizedType, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<bpftrace::SizedType>, bpftrace::SizedType const&>(std::_Sp_alloc_shared_tag<std::allocator<bpftrace::SizedType> >, bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr_base.h:1371
    #6 0x555a2d8bb5f4 in std::shared_ptr<bpftrace::SizedType>::shared_ptr<std::allocator<bpftrace::SizedType>, bpftrace::SizedType const&>(std::_Sp_alloc_shared_tag<std::allocator<bpftrace::SizedType> >, bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr.h:408
    #7 0x555a2d8bb519 in std::shared_ptr<bpftrace::SizedType> std::allocate_shared<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, bpftrace::SizedType const&>(std::allocator<bpftrace::SizedType> const&, bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr.h:860
    #8 0x555a2d8bb43d in std::shared_ptr<bpftrace::SizedType> std::make_shared<bpftrace::SizedType, bpftrace::SizedType const&>(bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr.h:876
    #9 0x555a2d8b70f7 in bpftrace::CreatePointer(bpftrace::SizedType const&, bpftrace::AddrSpace) /vagrant/src/types.cpp:354
    #10 0x555a2d869aec in get_sized_type /vagrant/src/clang_parser.cpp:328
    #11 0x555a2d869b9e in get_sized_type /vagrant/src/clang_parser.cpp:339
    #12 0x555a2d86abad in operator() /vagrant/src/clang_parser.cpp:543
    #13 0x555a2d86ae9d in _FUN /vagrant/src/clang_parser.cpp:577
    #14 0x7fa175ea36f1  (/usr/lib/llvm-12/lib/libclang-12.so.1+0x4456f1)

Indirect leak of 1536 byte(s) in 1 object(s) allocated from:
    #0 0x7fa1773ce5a7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x7fa1723fb2be  (/usr/lib/llvm-12/lib/libLLVM-12.so.1+0x21972be)

Indirect leak of 1536 byte(s) in 1 object(s) allocated from:
    #0 0x7fa1773ce5a7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x7fa1723f560e  (/usr/lib/llvm-12/lib/libLLVM-12.so.1+0x219160e)

Indirect leak of 1024 byte(s) in 1 object(s) allocated from:
    #0 0x7fa1773ce5a7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x7fa1723f5c04  (/usr/lib/llvm-12/lib/libLLVM-12.so.1+0x2191c04)

Indirect leak of 912 byte(s) in 6 object(s) allocated from:
    #0 0x7fa1773ce5a7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x555a2d8bc11d in __gnu_cxx::new_allocator<std::_Sp_counted_ptr_inplace<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, (__gnu_cxx::_Lock_policy)2> >::allocate(unsigned long, void const*) /usr/include/c++/10/ext/new_allocator.h:115
    #2 0x555a2d8bbf16 in std::allocator_traits<std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, (__gnu_cxx::_Lock_policy)2> > >::allocate(std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, (__gnu_cxx::_Lock_policy)2> >&, unsigned long) /usr/include/c++/10/bits/alloc_traits.h:460
    #3 0x555a2d8bbb89 in std::__allocated_ptr<std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, (__gnu_cxx::_Lock_policy)2> > > std::__allocate_guarded<std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, (__gnu_cxx::_Lock_policy)2> > >(std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, (__gnu_cxx::_Lock_policy)2> >&) /usr/include/c++/10/bits/allocated_ptr.h:97
    #4 0x555a2d8bb90b in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, bpftrace::SizedType const&>(bpftrace::SizedType*&, std::_Sp_alloc_shared_tag<std::allocator<bpftrace::SizedType> >, bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr_base.h:680
    #5 0x555a2d8bb78f in std::__shared_ptr<bpftrace::SizedType, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<bpftrace::SizedType>, bpftrace::SizedType const&>(std::_Sp_alloc_shared_tag<std::allocator<bpftrace::SizedType> >, bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr_base.h:1371
    #6 0x555a2d8bb5f4 in std::shared_ptr<bpftrace::SizedType>::shared_ptr<std::allocator<bpftrace::SizedType>, bpftrace::SizedType const&>(std::_Sp_alloc_shared_tag<std::allocator<bpftrace::SizedType> >, bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr.h:408
    #7 0x555a2d8bb519 in std::shared_ptr<bpftrace::SizedType> std::allocate_shared<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, bpftrace::SizedType const&>(std::allocator<bpftrace::SizedType> const&, bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr.h:860
    #8 0x555a2d8bb43d in std::shared_ptr<bpftrace::SizedType> std::make_shared<bpftrace::SizedType, bpftrace::SizedType const&>(bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr.h:876
    #9 0x555a2d8b7045 in bpftrace::CreateArray(unsigned long, bpftrace::SizedType const&) /vagrant/src/types.cpp:346
    #10 0x555a2d869bc2 in get_sized_type /vagrant/src/clang_parser.cpp:340
    #11 0x555a2d869b9e in get_sized_type /vagrant/src/clang_parser.cpp:339
    #12 0x555a2d86abad in operator() /vagrant/src/clang_parser.cpp:543
    #13 0x555a2d86ae9d in _FUN /vagrant/src/clang_parser.cpp:577
    #14 0x7fa175ea36f1  (/usr/lib/llvm-12/lib/libclang-12.so.1+0x4456f1)

Indirect leak of 677 byte(s) in 35 object(s) allocated from:
    #0 0x7fa1773ce5a7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x555a2d7aa659 in void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*>(char*, char*, std::forward_iterator_tag) (/home/vagrant/build-asan/src/bpftrace+0xde659)
    #2 0x555a2d83fe98 in bpftrace::SizedType::SizedType(bpftrace::SizedType const&) (/home/vagrant/build-asan/src/bpftrace+0x173e98)
    #3 0x555a2d8bc1ec in void __gnu_cxx::new_allocator<bpftrace::SizedType>::construct<bpftrace::SizedType, bpftrace::SizedType const&>(bpftrace::SizedType*, bpftrace::SizedType const&) /usr/include/c++/10/ext/new_allocator.h:150
    #4 0x555a2d8bbffb in void std::allocator_traits<std::allocator<bpftrace::SizedType> >::construct<bpftrace::SizedType, bpftrace::SizedType const&>(std::allocator<bpftrace::SizedType>&, bpftrace::SizedType*, bpftrace::SizedType const&) /usr/include/c++/10/bits/alloc_traits.h:512
    #5 0x555a2d8bbcef in std::_Sp_counted_ptr_inplace<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<bpftrace::SizedType const&>(std::allocator<bpftrace::SizedType>, bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr_base.h:551
    #6 0x555a2d8bb963 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, bpftrace::SizedType const&>(bpftrace::SizedType*&, std::_Sp_alloc_shared_tag<std::allocator<bpftrace::SizedType> >, bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr_base.h:682
    #7 0x555a2d8bb78f in std::__shared_ptr<bpftrace::SizedType, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<bpftrace::SizedType>, bpftrace::SizedType const&>(std::_Sp_alloc_shared_tag<std::allocator<bpftrace::SizedType> >, bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr_base.h:1371
    #8 0x555a2d8bb5f4 in std::shared_ptr<bpftrace::SizedType>::shared_ptr<std::allocator<bpftrace::SizedType>, bpftrace::SizedType const&>(std::_Sp_alloc_shared_tag<std::allocator<bpftrace::SizedType> >, bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr.h:408
    #9 0x555a2d8bb519 in std::shared_ptr<bpftrace::SizedType> std::allocate_shared<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, bpftrace::SizedType const&>(std::allocator<bpftrace::SizedType> const&, bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr.h:860
    #10 0x555a2d8bb43d in std::shared_ptr<bpftrace::SizedType> std::make_shared<bpftrace::SizedType, bpftrace::SizedType const&>(bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr.h:876
    #11 0x555a2d8b7045 in bpftrace::CreateArray(unsigned long, bpftrace::SizedType const&) /vagrant/src/types.cpp:346
    #12 0x555a2d869bc2 in get_sized_type /vagrant/src/clang_parser.cpp:340
    #13 0x555a2d86abad in operator() /vagrant/src/clang_parser.cpp:543
    #14 0x555a2d86ae9d in _FUN /vagrant/src/clang_parser.cpp:577
    #15 0x7fa175ea36f1  (/usr/lib/llvm-12/lib/libclang-12.so.1+0x4456f1)

Indirect leak of 510 byte(s) in 24 object(s) allocated from:
    #0 0x7fa1773ce5a7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x555a2d7aa659 in void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*>(char*, char*, std::forward_iterator_tag) (/home/vagrant/build-asan/src/bpftrace+0xde659)
    #2 0x555a2d83fe98 in bpftrace::SizedType::SizedType(bpftrace::SizedType const&) (/home/vagrant/build-asan/src/bpftrace+0x173e98)
    #3 0x555a2d8bc1ec in void __gnu_cxx::new_allocator<bpftrace::SizedType>::construct<bpftrace::SizedType, bpftrace::SizedType const&>(bpftrace::SizedType*, bpftrace::SizedType const&) /usr/include/c++/10/ext/new_allocator.h:150
    #4 0x555a2d8bbffb in void std::allocator_traits<std::allocator<bpftrace::SizedType> >::construct<bpftrace::SizedType, bpftrace::SizedType const&>(std::allocator<bpftrace::SizedType>&, bpftrace::SizedType*, bpftrace::SizedType const&) /usr/include/c++/10/bits/alloc_traits.h:512
    #5 0x555a2d8bbcef in std::_Sp_counted_ptr_inplace<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<bpftrace::SizedType const&>(std::allocator<bpftrace::SizedType>, bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr_base.h:551
    #6 0x555a2d8bb963 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, bpftrace::SizedType const&>(bpftrace::SizedType*&, std::_Sp_alloc_shared_tag<std::allocator<bpftrace::SizedType> >, bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr_base.h:682
    #7 0x555a2d8bb78f in std::__shared_ptr<bpftrace::SizedType, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<bpftrace::SizedType>, bpftrace::SizedType const&>(std::_Sp_alloc_shared_tag<std::allocator<bpftrace::SizedType> >, bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr_base.h:1371
    #8 0x555a2d8bb5f4 in std::shared_ptr<bpftrace::SizedType>::shared_ptr<std::allocator<bpftrace::SizedType>, bpftrace::SizedType const&>(std::_Sp_alloc_shared_tag<std::allocator<bpftrace::SizedType> >, bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr.h:408
    #9 0x555a2d8bb519 in std::shared_ptr<bpftrace::SizedType> std::allocate_shared<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, bpftrace::SizedType const&>(std::allocator<bpftrace::SizedType> const&, bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr.h:860
    #10 0x555a2d8bb43d in std::shared_ptr<bpftrace::SizedType> std::make_shared<bpftrace::SizedType, bpftrace::SizedType const&>(bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr.h:876
    #11 0x555a2d8b70f7 in bpftrace::CreatePointer(bpftrace::SizedType const&, bpftrace::AddrSpace) /vagrant/src/types.cpp:354
    #12 0x555a2d869aec in get_sized_type /vagrant/src/clang_parser.cpp:328
    #13 0x555a2d869aca in get_sized_type /vagrant/src/clang_parser.cpp:328
    #14 0x555a2d86abad in operator() /vagrant/src/clang_parser.cpp:543
    #15 0x555a2d86ae9d in _FUN /vagrant/src/clang_parser.cpp:577
    #16 0x7fa175ea36f1  (/usr/lib/llvm-12/lib/libclang-12.so.1+0x4456f1)

Indirect leak of 504 byte(s) in 9 object(s) allocated from:
    #0 0x7fa1773ce5a7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x555a2d8ae969 in __gnu_cxx::new_allocator<std::_Sp_counted_ptr_inplace<bpftrace::Struct, std::allocator<bpftrace::Struct>, (__gnu_cxx::_Lock_policy)2> >::allocate(unsigned long, void const*) /usr/include/c++/10/ext/new_allocator.h:115
    #2 0x555a2d8ae76e in std::allocator_traits<std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::Struct, std::allocator<bpftrace::Struct>, (__gnu_cxx::_Lock_policy)2> > >::allocate(std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::Struct, std::allocator<bpftrace::Struct>, (__gnu_cxx::_Lock_policy)2> >&, unsigned long) /usr/include/c++/10/bits/alloc_traits.h:460
    #3 0x555a2d8ae389 in std::__allocated_ptr<std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::Struct, std::allocator<bpftrace::Struct>, (__gnu_cxx::_Lock_policy)2> > > std::__allocate_guarded<std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::Struct, std::allocator<bpftrace::Struct>, (__gnu_cxx::_Lock_policy)2> > >(std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::Struct, std::allocator<bpftrace::Struct>, (__gnu_cxx::_Lock_policy)2> >&) /usr/include/c++/10/bits/allocated_ptr.h:97
    #4 0x555a2d8adf99 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<bpftrace::Struct, std::allocator<bpftrace::Struct>, unsigned long&>(bpftrace::Struct*&, std::_Sp_alloc_shared_tag<std::allocator<bpftrace::Struct> >, unsigned long&) /usr/include/c++/10/bits/shared_ptr_base.h:680
    #5 0x555a2d8adc0b in std::__shared_ptr<bpftrace::Struct, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<bpftrace::Struct>, unsigned long&>(std::_Sp_alloc_shared_tag<std::allocator<bpftrace::Struct> >, unsigned long&) /usr/include/c++/10/bits/shared_ptr_base.h:1371
    #6 0x555a2d8ad3ea in std::shared_ptr<bpftrace::Struct>::shared_ptr<std::allocator<bpftrace::Struct>, unsigned long&>(std::_Sp_alloc_shared_tag<std::allocator<bpftrace::Struct> >, unsigned long&) /usr/include/c++/10/bits/shared_ptr.h:408
    #7 0x555a2d8ac66a in std::shared_ptr<bpftrace::Struct> std::allocate_shared<bpftrace::Struct, std::allocator<bpftrace::Struct>, unsigned long&>(std::allocator<bpftrace::Struct> const&, unsigned long&) /usr/include/c++/10/bits/shared_ptr.h:860
    #8 0x555a2d8abd4c in std::shared_ptr<bpftrace::Struct> std::make_shared<bpftrace::Struct, unsigned long&>(unsigned long&) /usr/include/c++/10/bits/shared_ptr.h:876
    #9 0x555a2d8aa946 in bpftrace::StructManager::LookupOrAdd(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long) /vagrant/src/struct.cpp:133
    #10 0x555a2d8699e3 in get_sized_type /vagrant/src/clang_parser.cpp:313
    #11 0x555a2d869aca in get_sized_type /vagrant/src/clang_parser.cpp:328
    #12 0x555a2d869b9e in get_sized_type /vagrant/src/clang_parser.cpp:339
    #13 0x555a2d86abad in operator() /vagrant/src/clang_parser.cpp:543
    #14 0x555a2d86ae9d in _FUN /vagrant/src/clang_parser.cpp:577
    #15 0x7fa175ea36f1  (/usr/lib/llvm-12/lib/libclang-12.so.1+0x4456f1)

Indirect leak of 455 byte(s) in 20 object(s) allocated from:
    #0 0x7fa1773ce5a7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x555a2d7aa659 in void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*>(char*, char*, std::forward_iterator_tag) (/home/vagrant/build-asan/src/bpftrace+0xde659)
    #2 0x555a2d83fe98 in bpftrace::SizedType::SizedType(bpftrace::SizedType const&) (/home/vagrant/build-asan/src/bpftrace+0x173e98)
    #3 0x555a2d8bc1ec in void __gnu_cxx::new_allocator<bpftrace::SizedType>::construct<bpftrace::SizedType, bpftrace::SizedType const&>(bpftrace::SizedType*, bpftrace::SizedType const&) /usr/include/c++/10/ext/new_allocator.h:150
    #4 0x555a2d8bbffb in void std::allocator_traits<std::allocator<bpftrace::SizedType> >::construct<bpftrace::SizedType, bpftrace::SizedType const&>(std::allocator<bpftrace::SizedType>&, bpftrace::SizedType*, bpftrace::SizedType const&) /usr/include/c++/10/bits/alloc_traits.h:512
    #5 0x555a2d8bbcef in std::_Sp_counted_ptr_inplace<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<bpftrace::SizedType const&>(std::allocator<bpftrace::SizedType>, bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr_base.h:551
    #6 0x555a2d8bb963 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, bpftrace::SizedType const&>(bpftrace::SizedType*&, std::_Sp_alloc_shared_tag<std::allocator<bpftrace::SizedType> >, bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr_base.h:682
    #7 0x555a2d8bb78f in std::__shared_ptr<bpftrace::SizedType, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<bpftrace::SizedType>, bpftrace::SizedType const&>(std::_Sp_alloc_shared_tag<std::allocator<bpftrace::SizedType> >, bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr_base.h:1371
    #8 0x555a2d8bb5f4 in std::shared_ptr<bpftrace::SizedType>::shared_ptr<std::allocator<bpftrace::SizedType>, bpftrace::SizedType const&>(std::_Sp_alloc_shared_tag<std::allocator<bpftrace::SizedType> >, bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr.h:408
    #9 0x555a2d8bb519 in std::shared_ptr<bpftrace::SizedType> std::allocate_shared<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, bpftrace::SizedType const&>(std::allocator<bpftrace::SizedType> const&, bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr.h:860
    #10 0x555a2d8bb43d in std::shared_ptr<bpftrace::SizedType> std::make_shared<bpftrace::SizedType, bpftrace::SizedType const&>(bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr.h:876
    #11 0x555a2d8b70f7 in bpftrace::CreatePointer(bpftrace::SizedType const&, bpftrace::AddrSpace) /vagrant/src/types.cpp:354
    #12 0x555a2d869aec in get_sized_type /vagrant/src/clang_parser.cpp:328
    #13 0x555a2d869b9e in get_sized_type /vagrant/src/clang_parser.cpp:339
    #14 0x555a2d86abad in operator() /vagrant/src/clang_parser.cpp:543
    #15 0x555a2d86ae9d in _FUN /vagrant/src/clang_parser.cpp:577
    #16 0x7fa175ea36f1  (/usr/lib/llvm-12/lib/libclang-12.so.1+0x4456f1)

Indirect leak of 336 byte(s) in 6 object(s) allocated from:
    #0 0x7fa1773ce5a7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x555a2d8ae969 in __gnu_cxx::new_allocator<std::_Sp_counted_ptr_inplace<bpftrace::Struct, std::allocator<bpftrace::Struct>, (__gnu_cxx::_Lock_policy)2> >::allocate(unsigned long, void const*) /usr/include/c++/10/ext/new_allocator.h:115
    #2 0x555a2d8ae76e in std::allocator_traits<std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::Struct, std::allocator<bpftrace::Struct>, (__gnu_cxx::_Lock_policy)2> > >::allocate(std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::Struct, std::allocator<bpftrace::Struct>, (__gnu_cxx::_Lock_policy)2> >&, unsigned long) /usr/include/c++/10/bits/alloc_traits.h:460
    #3 0x555a2d8ae389 in std::__allocated_ptr<std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::Struct, std::allocator<bpftrace::Struct>, (__gnu_cxx::_Lock_policy)2> > > std::__allocate_guarded<std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::Struct, std::allocator<bpftrace::Struct>, (__gnu_cxx::_Lock_policy)2> > >(std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::Struct, std::allocator<bpftrace::Struct>, (__gnu_cxx::_Lock_policy)2> >&) /usr/include/c++/10/bits/allocated_ptr.h:97
    #4 0x555a2d8adf99 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<bpftrace::Struct, std::allocator<bpftrace::Struct>, unsigned long&>(bpftrace::Struct*&, std::_Sp_alloc_shared_tag<std::allocator<bpftrace::Struct> >, unsigned long&) /usr/include/c++/10/bits/shared_ptr_base.h:680
    #5 0x555a2d8adc0b in std::__shared_ptr<bpftrace::Struct, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<bpftrace::Struct>, unsigned long&>(std::_Sp_alloc_shared_tag<std::allocator<bpftrace::Struct> >, unsigned long&) /usr/include/c++/10/bits/shared_ptr_base.h:1371
    #6 0x555a2d8ad3ea in std::shared_ptr<bpftrace::Struct>::shared_ptr<std::allocator<bpftrace::Struct>, unsigned long&>(std::_Sp_alloc_shared_tag<std::allocator<bpftrace::Struct> >, unsigned long&) /usr/include/c++/10/bits/shared_ptr.h:408
    #7 0x555a2d8ac66a in std::shared_ptr<bpftrace::Struct> std::allocate_shared<bpftrace::Struct, std::allocator<bpftrace::Struct>, unsigned long&>(std::allocator<bpftrace::Struct> const&, unsigned long&) /usr/include/c++/10/bits/shared_ptr.h:860
    #8 0x555a2d8abd4c in std::shared_ptr<bpftrace::Struct> std::make_shared<bpftrace::Struct, unsigned long&>(unsigned long&) /usr/include/c++/10/bits/shared_ptr.h:876
    #9 0x555a2d8aa946 in bpftrace::StructManager::LookupOrAdd(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long) /vagrant/src/struct.cpp:133
    #10 0x555a2d8699e3 in get_sized_type /vagrant/src/clang_parser.cpp:313
    #11 0x555a2d86abad in operator() /vagrant/src/clang_parser.cpp:543
    #12 0x555a2d86ae9d in _FUN /vagrant/src/clang_parser.cpp:577
    #13 0x7fa175ea36f1  (/usr/lib/llvm-12/lib/libclang-12.so.1+0x4456f1)

Indirect leak of 280 byte(s) in 5 object(s) allocated from:
    #0 0x7fa1773ce5a7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x555a2d8ae969 in __gnu_cxx::new_allocator<std::_Sp_counted_ptr_inplace<bpftrace::Struct, std::allocator<bpftrace::Struct>, (__gnu_cxx::_Lock_policy)2> >::allocate(unsigned long, void const*) /usr/include/c++/10/ext/new_allocator.h:115
    #2 0x555a2d8ae76e in std::allocator_traits<std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::Struct, std::allocator<bpftrace::Struct>, (__gnu_cxx::_Lock_policy)2> > >::allocate(std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::Struct, std::allocator<bpftrace::Struct>, (__gnu_cxx::_Lock_policy)2> >&, unsigned long) /usr/include/c++/10/bits/alloc_traits.h:460
    #3 0x555a2d8ae389 in std::__allocated_ptr<std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::Struct, std::allocator<bpftrace::Struct>, (__gnu_cxx::_Lock_policy)2> > > std::__allocate_guarded<std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::Struct, std::allocator<bpftrace::Struct>, (__gnu_cxx::_Lock_policy)2> > >(std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::Struct, std::allocator<bpftrace::Struct>, (__gnu_cxx::_Lock_policy)2> >&) /usr/include/c++/10/bits/allocated_ptr.h:97
    #4 0x555a2d8adf99 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<bpftrace::Struct, std::allocator<bpftrace::Struct>, unsigned long&>(bpftrace::Struct*&, std::_Sp_alloc_shared_tag<std::allocator<bpftrace::Struct> >, unsigned long&) /usr/include/c++/10/bits/shared_ptr_base.h:680
    #5 0x555a2d8adc0b in std::__shared_ptr<bpftrace::Struct, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<bpftrace::Struct>, unsigned long&>(std::_Sp_alloc_shared_tag<std::allocator<bpftrace::Struct> >, unsigned long&) /usr/include/c++/10/bits/shared_ptr_base.h:1371
    #6 0x555a2d8ad3ea in std::shared_ptr<bpftrace::Struct>::shared_ptr<std::allocator<bpftrace::Struct>, unsigned long&>(std::_Sp_alloc_shared_tag<std::allocator<bpftrace::Struct> >, unsigned long&) /usr/include/c++/10/bits/shared_ptr.h:408
    #7 0x555a2d8ac66a in std::shared_ptr<bpftrace::Struct> std::allocate_shared<bpftrace::Struct, std::allocator<bpftrace::Struct>, unsigned long&>(std::allocator<bpftrace::Struct> const&, unsigned long&) /usr/include/c++/10/bits/shared_ptr.h:860
    #8 0x555a2d8abd4c in std::shared_ptr<bpftrace::Struct> std::make_shared<bpftrace::Struct, unsigned long&>(unsigned long&) /usr/include/c++/10/bits/shared_ptr.h:876
    #9 0x555a2d8aa946 in bpftrace::StructManager::LookupOrAdd(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long) /vagrant/src/struct.cpp:133
    #10 0x555a2d8699e3 in get_sized_type /vagrant/src/clang_parser.cpp:313
    #11 0x555a2d869aca in get_sized_type /vagrant/src/clang_parser.cpp:328
    #12 0x555a2d869aca in get_sized_type /vagrant/src/clang_parser.cpp:328
    #13 0x555a2d86abad in operator() /vagrant/src/clang_parser.cpp:543
    #14 0x555a2d86ae9d in _FUN /vagrant/src/clang_parser.cpp:577
    #15 0x7fa175ea36f1  (/usr/lib/llvm-12/lib/libclang-12.so.1+0x4456f1)

Indirect leak of 272 byte(s) in 1 object(s) allocated from:
    #0 0x7fa1773ce5a7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x7fa1723eed24 in llvm::orc::ExecutionSession::createBareJITDylib(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) (/usr/lib/llvm-12/lib/libLLVM-12.so.1+0x218ad24)
    #2 0x555a2d8dbba5 in std::_MakeUniq<bpftrace::BpfOrc>::__single_object std::make_unique<bpftrace::BpfOrc, llvm::TargetMachine*, llvm::DataLayout>(llvm::TargetMachine*&&, llvm::DataLayout&&) /usr/include/c++/10/bits/unique_ptr.h:962
    #3 0x555a2d8d6b34 in bpftrace::BpfOrc::Create() /vagrant/src/bpforcv2.cpp:41
    #4 0x555a2d91549b in bpftrace::ast::CodegenLLVM::CodegenLLVM(bpftrace::ast::Node*, bpftrace::BPFtrace&) /vagrant/src/ast/codegen_llvm.cpp:34
    #5 0x555a2d782fc5 in main /vagrant/src/main.cpp:814
    #6 0x7fa16cac3564 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28564)

Indirect leak of 152 byte(s) in 1 object(s) allocated from:
    #0 0x7fa1773ce5a7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x555a2d8bc11d in __gnu_cxx::new_allocator<std::_Sp_counted_ptr_inplace<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, (__gnu_cxx::_Lock_policy)2> >::allocate(unsigned long, void const*) /usr/include/c++/10/ext/new_allocator.h:115
    #2 0x555a2d8bbf16 in std::allocator_traits<std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, (__gnu_cxx::_Lock_policy)2> > >::allocate(std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, (__gnu_cxx::_Lock_policy)2> >&, unsigned long) /usr/include/c++/10/bits/alloc_traits.h:460
    #3 0x555a2d8bbb89 in std::__allocated_ptr<std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, (__gnu_cxx::_Lock_policy)2> > > std::__allocate_guarded<std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, (__gnu_cxx::_Lock_policy)2> > >(std::allocator<std::_Sp_counted_ptr_inplace<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, (__gnu_cxx::_Lock_policy)2> >&) /usr/include/c++/10/bits/allocated_ptr.h:97
    #4 0x555a2d8bb90b in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, bpftrace::SizedType const&>(bpftrace::SizedType*&, std::_Sp_alloc_shared_tag<std::allocator<bpftrace::SizedType> >, bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr_base.h:680
    #5 0x555a2d8bb78f in std::__shared_ptr<bpftrace::SizedType, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<bpftrace::SizedType>, bpftrace::SizedType const&>(std::_Sp_alloc_shared_tag<std::allocator<bpftrace::SizedType> >, bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr_base.h:1371
    #6 0x555a2d8bb5f4 in std::shared_ptr<bpftrace::SizedType>::shared_ptr<std::allocator<bpftrace::SizedType>, bpftrace::SizedType const&>(std::_Sp_alloc_shared_tag<std::allocator<bpftrace::SizedType> >, bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr.h:408
    #7 0x555a2d8bb519 in std::shared_ptr<bpftrace::SizedType> std::allocate_shared<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, bpftrace::SizedType const&>(std::allocator<bpftrace::SizedType> const&, bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr.h:860
    #8 0x555a2d8bb43d in std::shared_ptr<bpftrace::SizedType> std::make_shared<bpftrace::SizedType, bpftrace::SizedType const&>(bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr.h:876
    #9 0x555a2d8b70f7 in bpftrace::CreatePointer(bpftrace::SizedType const&, bpftrace::AddrSpace) /vagrant/src/types.cpp:354
    #10 0x555a2d869aec in get_sized_type /vagrant/src/clang_parser.cpp:328
    #11 0x555a2d869aca in get_sized_type /vagrant/src/clang_parser.cpp:328
    #12 0x555a2d869b9e in get_sized_type /vagrant/src/clang_parser.cpp:339
    #13 0x555a2d86abad in operator() /vagrant/src/clang_parser.cpp:543
    #14 0x555a2d86ae9d in _FUN /vagrant/src/clang_parser.cpp:577
    #15 0x7fa175ea36f1  (/usr/lib/llvm-12/lib/libclang-12.so.1+0x4456f1)

Indirect leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x7fa1773ce5a7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x7fa172402fd1 in llvm::orc::DynamicLibrarySearchGenerator::Load(char const*, char, std::function<bool (llvm::orc::SymbolStringPtr const&)>) (/usr/lib/llvm-12/lib/libLLVM-12.so.1+0x219efd1)

Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7fa1773ce5a7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x555a2d8e1d86 in __gnu_cxx::new_allocator<std::_Sp_counted_deleter<llvm::orc::DynamicLibrarySearchGenerator*, std::default_delete<llvm::orc::DynamicLibrarySearchGenerator>, std::allocator<void>, (__gnu_cxx::_Lock_policy)2> >::allocate(unsigned long, void const*) /usr/include/c++/10/ext/new_allocator.h:115
    #2 0x555a2d8e1190 in std::allocator_traits<std::allocator<std::_Sp_counted_deleter<llvm::orc::DynamicLibrarySearchGenerator*, std::default_delete<llvm::orc::DynamicLibrarySearchGenerator>, std::allocator<void>, (__gnu_cxx::_Lock_policy)2> > >::allocate(std::allocator<std::_Sp_counted_deleter<llvm::orc::DynamicLibrarySearchGenerator*, std::default_delete<llvm::orc::DynamicLibrarySearchGenerator>, std::allocator<void>, (__gnu_cxx::_Lock_policy)2> >&, unsigned long) /usr/include/c++/10/bits/alloc_traits.h:460
    #3 0x555a2d8e034f in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<llvm::orc::DynamicLibrarySearchGenerator, std::default_delete<llvm::orc::DynamicLibrarySearchGenerator> >(std::unique_ptr<llvm::orc::DynamicLibrarySearchGenerator, std::default_delete<llvm::orc::DynamicLibrarySearchGenerator> >&&) /usr/include/c++/10/bits/shared_ptr_base.h:718
    #4 0x555a2d8df266 in std::__shared_ptr<llvm::orc::DefinitionGenerator, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<llvm::orc::DynamicLibrarySearchGenerator, std::default_delete<llvm::orc::DynamicLibrarySearchGenerator>, void>(std::unique_ptr<llvm::orc::DynamicLibrarySearchGenerator, std::default_delete<llvm::orc::DynamicLibrarySearchGenerator> >&&) /usr/include/c++/10/bits/shared_ptr_base.h:1221
    #5 0x555a2d8ddabd in std::shared_ptr<llvm::orc::DefinitionGenerator>::shared_ptr<llvm::orc::DynamicLibrarySearchGenerator, std::default_delete<llvm::orc::DynamicLibrarySearchGenerator>, void>(std::unique_ptr<llvm::orc::DynamicLibrarySearchGenerator, std::default_delete<llvm::orc::DynamicLibrarySearchGenerator> >&&) /usr/include/c++/10/bits/shared_ptr.h:340
    #6 0x555a2d8da8ef in llvm::orc::DynamicLibrarySearchGenerator& llvm::orc::JITDylib::addGenerator<llvm::orc::DynamicLibrarySearchGenerator>(std::unique_ptr<llvm::orc::DynamicLibrarySearchGenerator, std::default_delete<llvm::orc::DynamicLibrarySearchGenerator> >) /usr/include/llvm-12/llvm/ExecutionEngine/Orc/Core.h:1520
    #7 0x555a2d8d67a9 in bpftrace::BpfOrc::BpfOrc(llvm::TargetMachine*, llvm::DataLayout) /vagrant/src/bpforcv2.cpp:19
    #8 0x555a2d8dbba5 in std::_MakeUniq<bpftrace::BpfOrc>::__single_object std::make_unique<bpftrace::BpfOrc, llvm::TargetMachine*, llvm::DataLayout>(llvm::TargetMachine*&&, llvm::DataLayout&&) /usr/include/c++/10/bits/unique_ptr.h:962
    #9 0x555a2d8d6b34 in bpftrace::BpfOrc::Create() /vagrant/src/bpforcv2.cpp:41
    #10 0x555a2d91549b in bpftrace::ast::CodegenLLVM::CodegenLLVM(bpftrace::ast::Node*, bpftrace::BPFtrace&) /vagrant/src/ast/codegen_llvm.cpp:34
    #11 0x555a2d782fc5 in main /vagrant/src/main.cpp:814
    #12 0x7fa16cac3564 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28564)

Indirect leak of 21 byte(s) in 1 object(s) allocated from:
    #0 0x7fa1773ce5a7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x555a2d7aa659 in void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*>(char*, char*, std::forward_iterator_tag) (/home/vagrant/build-asan/src/bpftrace+0xde659)
    #2 0x555a2d83fe98 in bpftrace::SizedType::SizedType(bpftrace::SizedType const&) (/home/vagrant/build-asan/src/bpftrace+0x173e98)
    #3 0x555a2d8bc1ec in void __gnu_cxx::new_allocator<bpftrace::SizedType>::construct<bpftrace::SizedType, bpftrace::SizedType const&>(bpftrace::SizedType*, bpftrace::SizedType const&) /usr/include/c++/10/ext/new_allocator.h:150
    #4 0x555a2d8bbffb in void std::allocator_traits<std::allocator<bpftrace::SizedType> >::construct<bpftrace::SizedType, bpftrace::SizedType const&>(std::allocator<bpftrace::SizedType>&, bpftrace::SizedType*, bpftrace::SizedType const&) /usr/include/c++/10/bits/alloc_traits.h:512
    #5 0x555a2d8bbcef in std::_Sp_counted_ptr_inplace<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<bpftrace::SizedType const&>(std::allocator<bpftrace::SizedType>, bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr_base.h:551
    #6 0x555a2d8bb963 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, bpftrace::SizedType const&>(bpftrace::SizedType*&, std::_Sp_alloc_shared_tag<std::allocator<bpftrace::SizedType> >, bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr_base.h:682
    #7 0x555a2d8bb78f in std::__shared_ptr<bpftrace::SizedType, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<bpftrace::SizedType>, bpftrace::SizedType const&>(std::_Sp_alloc_shared_tag<std::allocator<bpftrace::SizedType> >, bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr_base.h:1371
    #8 0x555a2d8bb5f4 in std::shared_ptr<bpftrace::SizedType>::shared_ptr<std::allocator<bpftrace::SizedType>, bpftrace::SizedType const&>(std::_Sp_alloc_shared_tag<std::allocator<bpftrace::SizedType> >, bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr.h:408
    #9 0x555a2d8bb519 in std::shared_ptr<bpftrace::SizedType> std::allocate_shared<bpftrace::SizedType, std::allocator<bpftrace::SizedType>, bpftrace::SizedType const&>(std::allocator<bpftrace::SizedType> const&, bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr.h:860
    #10 0x555a2d8bb43d in std::shared_ptr<bpftrace::SizedType> std::make_shared<bpftrace::SizedType, bpftrace::SizedType const&>(bpftrace::SizedType const&) /usr/include/c++/10/bits/shared_ptr.h:876
    #11 0x555a2d8b70f7 in bpftrace::CreatePointer(bpftrace::SizedType const&, bpftrace::AddrSpace) /vagrant/src/types.cpp:354
    #12 0x555a2d869aec in get_sized_type /vagrant/src/clang_parser.cpp:328
    #13 0x555a2d869aca in get_sized_type /vagrant/src/clang_parser.cpp:328
    #14 0x555a2d869b9e in get_sized_type /vagrant/src/clang_parser.cpp:339
    #15 0x555a2d86abad in operator() /vagrant/src/clang_parser.cpp:543
    #16 0x555a2d86ae9d in _FUN /vagrant/src/clang_parser.cpp:577
    #17 0x7fa175ea36f1  (/usr/lib/llvm-12/lib/libclang-12.so.1+0x4456f1)

Indirect leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7fa1773ce5a7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x7fa1723f7d55 in void std::vector<std::pair<llvm::orc::JITDylib*, llvm::orc::JITDylibLookupFlags>, std::allocator<std::pair<llvm::orc::JITDylib*, llvm::orc::JITDylibLookupFlags> > >::_M_realloc_insert<std::pair<llvm::orc::JITDylib*, llvm::orc::JITDylibLookupFlags> >(__gnu_cxx::__normal_iterator<std::pair<llvm::orc::JITDylib*, llvm::orc::JITDylibLookupFlags>*, std::vector<std::pair<llvm::orc::JITDylib*, llvm::orc::JITDylibLookupFlags>, std::allocator<std::pair<llvm::orc::JITDylib*, llvm::orc::JITDylibLookupFlags> > > >, std::pair<llvm::orc::JITDylib*, llvm::orc::JITDylibLookupFlags>&&) (/usr/lib/llvm-12/lib/libLLVM-12.so.1+0x2193d55)

Indirect leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7fa1773ce5a7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x555a2d8e262b in __gnu_cxx::new_allocator<std::shared_ptr<llvm::orc::DefinitionGenerator> >::allocate(unsigned long, void const*) /usr/include/c++/10/ext/new_allocator.h:115
    #2 0x555a2d8e1f06 in std::allocator_traits<std::allocator<std::shared_ptr<llvm::orc::DefinitionGenerator> > >::allocate(std::allocator<std::shared_ptr<llvm::orc::DefinitionGenerator> >&, unsigned long) /usr/include/c++/10/bits/alloc_traits.h:460
    #3 0x555a2d8e1423 in std::_Vector_base<std::shared_ptr<llvm::orc::DefinitionGenerator>, std::allocator<std::shared_ptr<llvm::orc::DefinitionGenerator> > >::_M_allocate(unsigned long) /usr/include/c++/10/bits/stl_vector.h:346
    #4 0x555a2d8e0522 in void std::vector<std::shared_ptr<llvm::orc::DefinitionGenerator>, std::allocator<std::shared_ptr<llvm::orc::DefinitionGenerator> > >::_M_realloc_insert<std::shared_ptr<llvm::orc::DefinitionGenerator> >(__gnu_cxx::__normal_iterator<std::shared_ptr<llvm::orc::DefinitionGenerator>*, std::vector<std::shared_ptr<llvm::orc::DefinitionGenerator>, std::allocator<std::shared_ptr<llvm::orc::DefinitionGenerator> > > >, std::shared_ptr<llvm::orc::DefinitionGenerator>&&) /usr/include/c++/10/bits/vector.tcc:440
    #5 0x555a2d8df383 in std::shared_ptr<llvm::orc::DefinitionGenerator>& std::vector<std::shared_ptr<llvm::orc::DefinitionGenerator>, std::allocator<std::shared_ptr<llvm::orc::DefinitionGenerator> > >::emplace_back<std::shared_ptr<llvm::orc::DefinitionGenerator> >(std::shared_ptr<llvm::orc::DefinitionGenerator>&&) /usr/include/c++/10/bits/vector.tcc:121
    #6 0x555a2d8ddaf7 in std::vector<std::shared_ptr<llvm::orc::DefinitionGenerator>, std::allocator<std::shared_ptr<llvm::orc::DefinitionGenerator> > >::push_back(std::shared_ptr<llvm::orc::DefinitionGenerator>&&) /usr/include/c++/10/bits/stl_vector.h:1204
    #7 0x555a2d8da8fe in llvm::orc::DynamicLibrarySearchGenerator& llvm::orc::JITDylib::addGenerator<llvm::orc::DynamicLibrarySearchGenerator>(std::unique_ptr<llvm::orc::DynamicLibrarySearchGenerator, std::default_delete<llvm::orc::DynamicLibrarySearchGenerator> >) /usr/include/llvm-12/llvm/ExecutionEngine/Orc/Core.h:1520
    #8 0x555a2d8d67a9 in bpftrace::BpfOrc::BpfOrc(llvm::TargetMachine*, llvm::DataLayout) /vagrant/src/bpforcv2.cpp:19
    #9 0x555a2d8dbba5 in std::_MakeUniq<bpftrace::BpfOrc>::__single_object std::make_unique<bpftrace::BpfOrc, llvm::TargetMachine*, llvm::DataLayout>(llvm::TargetMachine*&&, llvm::DataLayout&&) /usr/include/c++/10/bits/unique_ptr.h:962
    #10 0x555a2d8d6b34 in bpftrace::BpfOrc::Create() /vagrant/src/bpforcv2.cpp:41
    #11 0x555a2d91549b in bpftrace::ast::CodegenLLVM::CodegenLLVM(bpftrace::ast::Node*, bpftrace::BPFtrace&) /vagrant/src/ast/codegen_llvm.cpp:34
    #12 0x555a2d782fc5 in main /vagrant/src/main.cpp:814
    #13 0x7fa16cac3564 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28564)

Indirect leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7fa1773ce5a7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x7fa1723e3c2a in llvm::orc::JITDylib::getDefaultResourceTracker() (/usr/lib/llvm-12/lib/libLLVM-12.so.1+0x217fc2a)
    #2 0x555a2d8d6ce3 in bpftrace::BpfOrc::compile(std::unique_ptr<llvm::Module, std::default_delete<llvm::Module> >) /vagrant/src/bpforcv2.cpp:46
    #3 0x555a2d92e039 in bpftrace::ast::CodegenLLVM::emit() /vagrant/src/ast/codegen_llvm.cpp:2955
    #4 0x555a2d7831af in main /vagrant/src/main.cpp:841
    #5 0x7fa16cac3564 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28564)

Indirect leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7fa1773ce5a7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x7fa1723fc3b3 in void std::vector<std::shared_ptr<llvm::orc::AsynchronousSymbolQuery>, std::allocator<std::shared_ptr<llvm::orc::AsynchronousSymbolQuery> > >::_M_realloc_insert<std::shared_ptr<llvm::orc::AsynchronousSymbolQuery> >(__gnu_cxx::__normal_iterator<std::shared_ptr<llvm::orc::AsynchronousSymbolQuery>*, std::vector<std::shared_ptr<llvm::orc::AsynchronousSymbolQuery>, std::allocator<std::shared_ptr<llvm::orc::AsynchronousSymbolQuery> > > >, std::shared_ptr<llvm::orc::AsynchronousSymbolQuery>&&) (/usr/lib/llvm-12/lib/libLLVM-12.so.1+0x21983b3)
    #2 0x60b00006d06f  (<unknown module>)

SUMMARY: AddressSanitizer: 1980542 byte(s) leaked in 5530 allocation(s).
```

Its not as bad as it was prior to #1878 but we're still leaking quite a bit of mem (1.8M) when parsing a lot of C headers (like tcplife does). As most of this comes from clang it increases with every include we add:

no include:     SUMMARY: AddressSanitizer: 9632 byte(s) leaked in 11 allocation(s).
linux/fs.h:       SUMMARY: AddressSanitizer: 597210 byte(s) leaked in 1712 allocation(s). (+587578)
 +mm.h:          SUMMARY: AddressSanitizer: 616427 byte(s) leaked in 1768 allocation(s). (+19217)
 +skbuff.h:     SUMMARY: AddressSanitizer: 818461 byte(s) leaked in 2301 allocation(s). (+202034)

Would be nice if we can fix them and add some regression testing to the ci.

### PR DESCRIPTION
**Pull request by viktormalik**
Using `std::shared_ptr` to store the inner struct in `SizedType` causes memleaks when working with recursive types (due to cycles in shared pointers). This PR replaces the `std::shared_ptr` by a raw pointer.

Fixes #1879.

##### Checklist

- [ ] Language changes are updated in `docs/reference_guide.md`
- [x] User-visible and non-trivial changes updated in `CHANGELOG.md`
- [ ] The new behaviour is covered by tests

### CODE REVIEW

File: src/struct.h [hunk 1]
```diff
@@ -68,12 +68,14 @@ class StructManager
...
-  std::shared_ptr<Struct> LookupOrAdd(const std::string &name, size_t size);
+  Struct *AddTuple(std::vector<SizedType> fields);
+  Struct *Lookup(const std::string &name) const;
+  Struct *LookupOrAdd(const std::string &name, size_t size);
   bool Has(const std::string &name) const;
 
 private:
-  std::map<std::string, std::shared_ptr<Struct>> struct_map_;
+  std::map<std::string, std::unique_ptr<Struct>> struct_map_;
+  std::vector<std::unique_ptr<Struct>> tuples_;
```
Comment (viktormalik) [inline src/struct.h:78]: Note: to maintain the same interface for structs and tuples in `SizedType`, I moved the tuple structure to `StructManager`.

File: src/struct.cpp [hunk 2]
```diff
@@ -118,25 +118,30 @@ void StructManager::Add(const std::string &name, size_t size)
...
+  return s != struct_map_.end() ? s->second.get() : nullptr;
 }
 
-std::shared_ptr<Struct> StructManager::LookupOrAdd(const std::string &name,
-                                                   size_t size)
+Struct *StructManager::LookupOrAdd(const std::string &name, size_t size)
 {
-  auto s = struct_map_.insert({ name, std::make_shared<Struct>(size) });
-  return s.first->second;
+  auto s = struct_map_.insert({ name, std::make_unique<Struct>(size) });
```
Comment (danobi) [inline src/struct.cpp:132]: Not related to this PR but just noticed: can't `LookupOrAdd()` overwrite existing data? Should we add an error check here?

File: src/types.h [hunk 3]
```diff
@@ -111,7 +111,8 @@ class SizedType
   AddrSpace as_ = AddrSpace::none;
   ssize_t size_bits_ = -1; // size in bits for integer types
 
-  std::shared_ptr<Struct> inner_struct_; // inner struct for records and tuples
+  Struct *inner_struct_; // inner struct for records and tuples
+                         // the actual Struct object is stored in StructManager
```
Comment (danobi) [inline src/types.h:115]:
```suggestion
                         // the actual Struct object is owned by StructManager
```

**Review by danobi — COMMENTED** [review]
So I see in `SemanticAnalyser::visit(Tuple &tuple)` I see an unconditional `CreateTuple()`. Doesn't this cause us to store 10x the values in `StructManager::tuples_`? If so, anything we can do to avoid that?

File: src/struct.cpp (hunk 2 above)
Comment (viktormalik) [reply src/struct.cpp:132]: It can't, `std::map::insert` inserts a new element only if the key is not in the map. Otherwise, it just returns an iterator to the existing element.

**Comment by viktormalik** [comment]
> So I see in `SemanticAnalyser::visit(Tuple &tuple)` I see an unconditional `CreateTuple()`. Doesn't this cause us to store 10x the values in `StructManager::tuples_`? If so, anything we can do to avoid that?

You're right, this is unnecessary. Two solutions come to mind:
1. Only store the type in the first/last iteration of the semantic analyser, which is easy, though I'm not sure if it's correct.
2. Change `StructManager::tuples_` into a hash map, then we'd have each tuple type stored only once. The hash could be the string representation of the `SizedType` (obtained by `operator<<`), which should be fine for this purpose, I hope.

**Comment by danobi** [comment]
Option 1 sounds incorrect although I haven't thought about it too hard.

Option 2 sounds reasonable to me. Couple thoughts on option 2:
* Using a string representation as key would work. But maybe also check if we can implement `std::hash` for `SizedType` so it could just be a a `std::unordered_set`. `std::unique_ptr` already implements `std::hash`: https://en.cppreference.com/w/cpp/memory/unique_ptr/hash . `SizedType` being hashable sounds generally useful to have (though I wouldn't go crazy over this to 
* Tuples types may change at each pass. We'll still be leaving behind the old, unused tuple types. Out of scope for this PR but I wonder if we can get rid of `is_final_pass()` altogether. It not only is not guaranteed to work (what if something takes 11 passes to resolve?) but causes subtle issues like this.

**Comment by viktormalik** [comment]
> * Using a string representation as key would work. But maybe also check if we can implement `std::hash` for `SizedType` so it could just be a a `std::unordered_set`. `std::unique_ptr` already implements `std::hash`: https://en.cppreference.com/w/cpp/memory/unique_ptr/hash . `SizedType` being hashable sounds generally useful to have (though I wouldn't go crazy over this to

I implemented `std::hash` for `SizedType` so now `StructManager::tuples_` is an `unordered_set`. It seems to work without problems but it definitely needs a detailed review.

> * Tuples types may change at each pass. We'll still be leaving behind the old, unused tuple types. Out of scope for this PR but I wonder if we can get rid of `is_final_pass()` altogether. It not only is not guaranteed to work (what if something takes 11 passes to resolve?) but causes subtle issues like this.

I'm not sure if getting rid of `is_final_pass` would help here as we leave unused types behind in cases when the type changes between passes, which would still happen.

Still, the approach of running a fixed number of 10 iterations is not very good, but that's for another discussion. We could be able to implement a more "clever" AST pass that would not re-visit nodes for which the state didn't change in 2 successive iterations. Then we could get rid of `is_final_pass` as we'd just run the semantic analysis until the fixpoint is found.

**Comment by danobi** [comment]
> I'm not sure if getting rid of is_final_pass would help here as we leave unused types behind in cases when the type changes between passes, which would still happen.

So I think `is_final_pass()` exists b/c maps are not always declared before they are used (needs citation). So in theory, if we could figure out the exact types of all the maps before we figure out the rest of the types, we only need a single pass, as non-maps are declared + defined at the same time.

But I agree, we should discuss this somewhere else.

**Comment by fbs** [comment]
I originally tagged this for the 0.13 release but I'm hoping to do that release on the first.  Should we try and get this in or just leave it for the next release? The leak isn't too bad

File: src/types.cpp [hunk 4]
```diff
@@ -541,3 +541,30 @@ const Struct *SizedType::GetStruct() const
...
+size_t hash<bpftrace::SizedType>::operator()(
+    const bpftrace::SizedType &type) const
+{
+  auto hash = std::hash<unsigned>()(static_cast<unsigned>(type.type));
+  bpftrace::hash_combine(hash, type.GetSize());
+
+  if (type.IsIntegerTy())
+    bpftrace::hash_combine(hash, type.IsSigned());
+  else if (type.IsRecordTy())
+    bpftrace::hash_combine(hash, type.GetName());
```
Comment (danobi) [inline src/types.cpp:555]: Shouldn't this be the hash of `inner_struct_`?

File: src/types.cpp [hunk 5]
```diff
@@ -541,3 +541,30 @@ const Struct *SizedType::GetStruct() const
...
+    bpftrace::hash_combine(hash, *type.GetPointeeTy());
+  else if (type.IsArrayTy())
+  {
+    bpftrace::hash_combine(hash, *type.GetElementTy());
+    bpftrace::hash_combine(hash, type.GetNumElements());
+  }
+  else if (type.IsTupleTy())
+    bpftrace::hash_combine(hash, *type.GetStruct());
+  else if (type.IsStack())
+    bpftrace::hash_combine(hash, type.stack_type);
```
Comment (danobi) [inline src/types.cpp:566]: Instead of if/else block, can this be a switch/case where we explicitly ignore some types (with no default case)?. That way if new types are added we'll get a compiler error instead of silent error.

**Comment by danobi** [comment]
> I originally tagged this for the 0.13 release but I'm hoping to do that release on the first. Should we try and get this in or just leave it for the next release? The leak isn't too bad

If we can get it in by the 1st that'd be nice. If not, not a huge deal IMO

File: src/types.cpp (hunk 4 above)
Comment (viktormalik) [reply src/types.cpp:555]: The `IsEqual` method compares structs by name, so I followed that behaviour. Both options should be correct as we don't have redefined types, but I have no problem changing this to hash the `inner_struct_` (though I'd change the `IsEqual` method, too). 

The question is if we want to have the same hash for two distinctly named types that have the same inner structure.

**Comment by viktormalik** [comment]
> > I originally tagged this for the 0.13 release but I'm hoping to do that release on the first. Should we try and get this in or just leave it for the next release? The leak isn't too bad
> 
> If we can get it in by the 1st that'd be nice. If not, not a huge deal IMO

Updated based on @danobi's review. Should be ready for merge if we want to get this in.

**Review by danobi — APPROVED** [review]
Discussed on IRC: this PR has potential to cause subtle bugs. So better if we let this get tested through another development cycle to iron out issues.

File: CHANGELOG.md [hunk 6]
```diff
@@ -43,6 +43,8 @@ and this project adheres to
   - [#1866](https://github.com/iovisor/bpftrace/pull/1866)
 - Fix memory leak in clang parser
   - [#1878](https://github.com/iovisor/bpftrace/pull/1878)
+- Fix memory leaks in struct types
```
Comment (fbs) [inline CHANGELOG.md:46]: wrong section due to 0.13 release, needs rebase

**Review by fbs — CHANGES_REQUESTED** [review]

File: CHANGELOG.md (hunk 6 above)
Comment (viktormalik) [reply CHANGELOG.md]: rebased
