### PR TITLE
codegen: Fix crash when attaching to invalid attachpoint

### LINKED ISSUE #1952: Segmentation fault when a USDT semaphore is declared but not used
### What reproduces the bug?
Consider the following code declaring USDTs with Folly:
```c++
#include <iostream>
#include <folly/tracing/StaticTracepoint.h>

FOLLY_SDT_DEFINE_SEMAPHORE(felix, initialize)

void initialize()
{
        if (FOLLY_SDT_IS_ENABLED(felix, initialize)) {
                std::cerr << "USDT tracing enabled" << std::endl;
        }
}

void launch()
{
        FOLLY_SDT(felix, launch, "foo");
}
```
When using bpftrace to activate the two tracepoints, we get a segfault:
```console
sudo bpftrace -e 'usdt:./libusdt-test.so:initialize { printf("initialize\n"); } usdt:./libusdt-test.so:launch { printf("launch: %s\n", str(arg0)); }'
Segmentation fault
```

The code above is probably not semantically valid for USDT, it is missing a `FOLLY_SDT(felix, initialize);` inside the `FOLLY_SDT_IS_ENABLED` condition, but I suppose it should not cause a segmentation fault.

With a debug bpftrace, we get an assert in llvm 12 instead:
```console
$ sudo gdb -batch -ex run -ex bt --args bpftrace -e 'usdt:./libusdt-test.so:initialize { printf("initialize\n"); } usdt:./libusdt-test.so:launch { printf("launch: %s\n", str(arg0)); }'
[...]

bpftrace: /usr/include/llvm-12/llvm/IR/Instructions.h:898: llvm::Type* llvm::checkGEPType(llvm::Type*): Assertion `Ty && "Invalid GetElementPtrInst indices for type!"' failed.

Thread 1 "bpftrace" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
49      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
#1  0x00007fffed526864 in __GI_abort () at abort.c:79
#2  0x00007fffed526749 in __assert_fail_base (fmt=0x7fffed6aff78 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x5555557be250 "Ty && \"Invalid GetElementPtrInst indices for type!\"", file=0x5555557be220 "/usr/include/llvm-12/llvm/IR/Instructions.h", line=898, function=<optimized out>) at assert.c:92
#3  0x00007fffed5383d6 in __GI___assert_fail (assertion=0x5555557be250 "Ty && \"Invalid GetElementPtrInst indices for type!\"", file=0x5555557be220 "/usr/include/llvm-12/llvm/IR/Instructions.h", line=898, function=0x5555557be1f0 "llvm::Type* llvm::checkGEPType(llvm::Type*)") at assert.c:101
#4  0x0000555555714c39 in llvm::checkGEPType (Ty=0x0) at /usr/include/llvm-12/llvm/IR/Instructions.h:898
#5  0x0000555555714df3 in llvm::GetElementPtrInst::getGEPReturnType (ElTy=0x555556183b90, Ptr=0x7fffe05b0a70, IdxList=...) at /usr/include/llvm-12/llvm/IR/Instructions.h:1075
#6  0x0000555555714f5a in llvm::GetElementPtrInst::GetElementPtrInst (this=0x555556189b80, PointeeType=0x555556183b90, Ptr=0x7fffe05b0a70, IdxList=..., Values=3, NameStr=..., InsertBefore=0x0) at /usr/include/llvm-12/llvm/IR/Instructions.h:1148
#7  0x0000555555714d4d in llvm::GetElementPtrInst::Create (PointeeType=0x555556183b90, Ptr=0x7fffe05b0a70, IdxList=..., NameStr=..., InsertBefore=0x0) at /usr/include/llvm-12/llvm/IR/Instructions.h:944
#8  0x0000555555717793 in llvm::IRBuilderBase::CreateGEP (this=0x7fffffffe198, Ty=0x0, Ptr=0x7fffe05b0a70, IdxList=..., Name=...) at /usr/include/llvm-12/llvm/IR/IRBuilder.h:1875
#9  0x000055555571765b in llvm::IRBuilderBase::CreateGEP (this=0x7fffffffe198, Ptr=0x7fffe05b0a70, IdxList=..., Name=...) at /usr/include/llvm-12/llvm/IR/IRBuilder.h:1861
#10 0x0000555555707c7c in bpftrace::ast::CodegenLLVM::createFormatStringCall (this=0x7fffffffe170, call=..., id=@0x7fffffffe348: 0, call_args=std::vector of length 2, capacity 2 = {...}, call_name="printf", async_action=bpftrace::AsyncAction::printf) at /home/fabecassis/github/bpftrace/src/ast/codegen_llvm.cpp:2784
#11 0x00005555556f8830 in bpftrace::ast::CodegenLLVM::visit (this=0x7fffffffe170, call=...) at /home/fabecassis/github/bpftrace/src/ast/codegen_llvm.cpp:842
#12 0x00005555556e0b0a in bpftrace::ast::Call::accept (this=0x5555559f2ca0, v=...) at /home/fabecassis/github/bpftrace/src/ast/ast.cpp:22
#13 0x000055555570a38f in bpftrace::ast::CodegenLLVM::accept (this=0x7fffffffe170, node=0x5555559f2ca0) at /home/fabecassis/github/bpftrace/src/ast/codegen_llvm.cpp:3063
#14 0x0000555555700d42 in bpftrace::ast::CodegenLLVM::visit (this=0x7fffffffe170, expr=...) at /home/fabecassis/github/bpftrace/src/ast/codegen_llvm.cpp:1844
#15 0x00005555556e0d2a in bpftrace::ast::ExprStatement::accept (this=0x7fffe0046560, v=...) at /home/fabecassis/github/bpftrace/src/ast/ast.cpp:32
#16 0x000055555570a38f in bpftrace::ast::CodegenLLVM::accept (this=0x7fffffffe170, node=0x7fffe0046560) at /home/fabecassis/github/bpftrace/src/ast/codegen_llvm.cpp:3063
#17 0x0000555555702835 in bpftrace::ast::CodegenLLVM::generateProbe (this=0x7fffffffe170, probe=..., full_func_id="./libusdt-test.so:felix:launch_loc0", section_name="usdt:./libusdt-test.so:felix:launch", func_type=0x555556183b10, expansion=true, usdt_location_index=std::optional<int> = {...}) at /home/fabecassis/github/bpftrace/src/ast/codegen_llvm.cpp:2155
#18 0x0000555555703496 in bpftrace::ast::CodegenLLVM::visit (this=0x7fffffffe170, probe=...) at /home/fabecassis/github/bpftrace/src/ast/codegen_llvm.cpp:2316
#19 0x00005555556e0f22 in bpftrace::ast::Probe::accept (this=0x7fffe00e5cf0, v=...) at /home/fabecassis/github/bpftrace/src/ast/ast.cpp:41
#20 0x000055555570a38f in bpftrace::ast::CodegenLLVM::accept (this=0x7fffffffe170, node=0x7fffe00e5cf0) at /home/fabecassis/github/bpftrace/src/ast/codegen_llvm.cpp:3063
#21 0x0000555555703afa in bpftrace::ast::CodegenLLVM::visit (this=0x7fffffffe170, program=...) at /home/fabecassis/github/bpftrace/src/ast/codegen_llvm.cpp:2366
#22 0x00005555556e0f5a in bpftrace::ast::Program::accept (this=0x7fffe00e60f0, v=...) at /home/fabecassis/github/bpftrace/src/ast/ast.cpp:42
#23 0x000055555570a38f in bpftrace::ast::CodegenLLVM::accept (this=0x7fffffffe170, node=0x7fffe00e60f0) at /home/fabecassis/github/bpftrace/src/ast/codegen_llvm.cpp:3063
#24 0x00005555557099bb in bpftrace::ast::CodegenLLVM::generate_ir (this=0x7fffffffe170) at /home/fabecassis/github/bpftrace/src/ast/codegen_llvm.cpp:2948
#25 0x000055555557e0cc in main (argc=3, argv=0x7fffffffeb48) at /home/fabecassis/github/bpftrace/src/main.cpp:829
```

### bpftrace --info
```console
$ sudo bpftrace --info
System
  OS: Linux 5.11.0-25-generic #27-Ubuntu SMP Fri Jul 9 23:06:29 UTC 2021
  Arch: x86_64

Build
  version: v0.13.0-61-g2775
  LLVM: 12.0.0
  ORC: v2
  foreach_sym: yes
  unsafe uprobe: no
  bfd: yes
  bpf_attach_kfunc: yes
  bcc_usdt_addsem: yes
  bcc bpf_attach_uprobe refcount: yes
  libbpf: yes
  libbpf btf dump: yes
  libbpf btf dump type decl: yes

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: yes
  probe_read_user_str: yes
  probe_read_kernel: yes
  probe_read_kernel_str: yes
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: yes
  get_boot_ns: yes
  dpath: yes

Kernel features
  Instruction limit: 1000000
  Loop support: yes
  btf (depends on Build:libbpf): yes
  map batch (depends on Build:libbpf): yes
  uprobe refcount (depends on Build:bcc bpf_attach_uprobe refcount): yes

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes

Probe types
  kprobe: yes
  tracepoint: yes
  perf_event: yes
  kfunc: yes
  iter:task: yes
  iter:task_file: yes
```

### PR DESCRIPTION
**Pull request by danobi**
This commit fixes a crash when attaching to a `need_expansion` probe
with an invalid attachpoint that uses an asyncid helper.

The root cause was that codegen increments the asyncids when visiting
helpers like `printf` and friends. However, if the attachpoint is
invalid (ie. `ProbeMatcher` does not find any attachpoints), then the
visiting is liable to be skipped. Thus, the asyncids are out of sync.
This can result in crashes inside LLVM b/c the types are all messed up.

See attached issue for more info.

This closes #1952 .

##### Checklist

- [ ] Language changes are updated in `man/adoc/bpftrace.adoc` and if needed in `docs/reference_guide.md`
- [ ] User-visible and non-trivial changes updated in `CHANGELOG.md`
- [ ] The new behaviour is covered by tests

### CODE REVIEW

File: src/ast/codegen_llvm.cpp [hunk 1]
```diff
@@ -2156,9 +2157,12 @@ void CodegenLLVM::generateProbe(Probe &probe,
   }
   createRet();
 
+  if (dummy)
+    func->eraseFromParent();
+
```
Comment (viktormalik) [inline src/ast/codegen_llvm.cpp:2162]: Why not like this (and without the `... && !dummy` below)?
```suggestion
  if (dummy)
  {
    func->eraseFromParent();
    return;
  }
```

Comment (danobi) [reply src/ast/codegen_llvm.cpp]: Yeah good point
