### PR TITLE
Fixup generated BTF for older kernels

### LINKED ISSUE #2913: type_id=3 vlen != 0 on 5.4 LTS kernel
Hi team,

when using the bleeding edge bpftrace static build on a centos7 with elrepo kernel (5.4/6.6)
I found that bt scripts with BEGIN {} is not working on bleeding bpftrace 0.19.0 binary combined 5.4 kernel.

I also tried from https://repos.baslab.org/rhel/7/bpftrace-daily/
bpftrace-0.14.1-1.202204049382ad1.el7.x86_64 , and it's working

1) 0.19.0 + 5.4 lts kernel
2) 0.19.0 + 6.6 lts kernel
3) 0.14.1 + 5.4 lts kernel

/2) and 3) are good.
/1) is not working.

./bpftrace -v -e 'BEGIN {printf("Hello eBPF"); exit();}'
INFO: node count: 8
Attaching 1 probe...

Error log: 
magic: 0xeb9f
version: 1
flags: 0x0
hdr_len: 24
type_off: 0
type_len: 76
str_off: 76
str_len: 50
btf_total_size: 150
[1] PTR (anon) type_id=2
[2] INT int8 size=1 bits_offset=0 nr_bits=8 encoding=SIGNED
[3] FUNC_PROTO (anon) return=4 args=(1 var1)
[4] INT int64 size=8 bits_offset=0 nr_bits=64 encoding=SIGNED
[5] FUNC BEGIN type_id=3 vlen != 0

ERROR: Error loading program: BEGIN
[root@VM-224-24-centos bpftrace-bleeding-edge]# uname -r
5.4.266-1.el7.elrepo.x86_64

=====

./bpftrace -v -e 'BEGIN {printf("Hello eBPF"); exit();}'
INFO: node count: 8
Attaching 1 probe...

Program ID: 4

The verifier log: 
processed 60 insns (limit 1000000) max_states_per_insn 0 total_states 4 peak_states 4 mark_read 2

Attaching BEGIN
Hello eBPF

[root@VM-224-24-centos bpftrace-bleeding-edge]# uname -r
6.6.10-1.el7.elrepo.x86_64

===== bpftrace --info on 5.4 lts kernel =====
System
  OS: Linux 5.4.266-1.el7.elrepo.x86_64 #1 SMP Mon Jan 8 23:23:50 EST 2024
  Arch: x86_64

Build
  version: v0.19.0
  LLVM: 17.0.6
  unsafe probe: no
  bfd: yes
  libdw (DWARF support): yes

libbpf: failed to find valid kernel BTF
Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: no
  probe_read_user_str: no
  probe_read_kernel: no
  probe_read_kernel_str: no
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: yes
  get_boot_ns: no
  dpath: no
  skboutput: no
  get_tai_ns: no
  get_func_ip: no
  jiffies64: no

Kernel features
  Instruction limit: 1000000
  Loop support: yes
  btf: no
  module btf: no
  map batch: no
  uprobe refcount (depends on Build:bcc bpf_attach_uprobe refcount): yes

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes
  ringbuf: no

Probe types
  kprobe: yes
  tracepoint: yes
  perf_event: yes
  kfunc: no
  kprobe_multi: no
  uprobe_multi: no
  raw_tp_special: no
  iter: no

====

I also tried watchpoint, and it failed with same reason.

./bpftrace -v -e "watchpoint:0x$(awk '$3 == "jiffies" {print $1}' /proc/kallsyms):8:w {@[kstack] = count();}"
INFO: node count: 7
Attaching 1 probe...

Error log: 
magic: 0xeb9f
version: 1
flags: 0x0
hdr_len: 24
type_off: 0
type_len: 76
str_off: 76
str_len: 102
btf_total_size: 202
[1] PTR (anon) type_id=2
[2] INT int8 size=1 bits_offset=0 nr_bits=8 encoding=SIGNED
[3] FUNC_PROTO (anon) return=4 args=(1 var1)
[4] INT int64 size=8 bits_offset=0 nr_bits=64 encoding=SIGNED
[5] FUNC watchpoint_18446744071601934336 type_id=3 vlen != 0

WARNING: Error loading program: watchpoint:18446744071601934336:8:w, skipping.
ERROR: Error attaching probe: watchpoint:18446744071601934336:8:w: Bad file descriptor

### PR DESCRIPTION
**Pull request by viktormalik**
Older kernels missing https://github.com/torvalds/linux/commit/51c39bb1d5d1 (most importantly the stable 5.4) do not support BTF function entries with global linkage (`BTF_FUNC_GLOBAL`). This causes them to reject our generated BTF for probes and prevents from running any bpftrace program.

In order to fix this, the generated BTF must be patched by replacing the `BTF_FUNC_GLOBAL` flag by 0. This is normally done by libbpf (https://github.com/torvalds/linux/commit/2d3eb67f64ec) but only when program loading via bpf_object is used. Since we're still using direct loading using `bpf_btf_load` and `bpf_prog_load`, we need to mimic libbpf's behavior and do the patching manually. Note that we cannot fix this directly in codegen b/c LLVM would optimize all our probes away.

The BTF fixup itself is pretty simple but required to copy a portion of code from libbpf internals. The reason is that libbpf doesn't export functions for iterating BTF in a non-const way.

This also requires to feature-detect support for `BTF_FUNC_GLOBAL`, so we extend `BPFfeature` with BTF feature detection.

Fixes #2913.

##### Checklist

- [ ] Language changes are updated in `man/adoc/bpftrace.adoc` and if needed in `docs/reference_guide.md`
- [x] User-visible and non-trivial changes updated in `CHANGELOG.md`
- [ ] The new behaviour is covered by tests

### CODE REVIEW

**Comment by viktormalik** [comment]
@xiaoqing-wei @the-prachi do you think you'd be able to test this fix on your setup? Unfortunately, we don't build static binaries for PRs but you could build it yourself by running `nix build .#appimage` with this PR checked out.

I was able to test this on my local reproducer of #2913 but would like to have a confirmation that it fixes the issue.

File: src/bpfbytecode.cpp [hunk 1]
```diff
@@ -25,4 +26,89 @@ const std::vector<uint8_t> &BpfBytecode::getSection(
...
+// This should go away once we move to bpf_object-based loading.
+//
+// Transformations done:
+// - If running on a kernel not supporting BTF func entries with BTF_FUNC_GLOBAL
+//   linkage, change the linkage type to 0. We cannot do this directly in
+//   codegen b/c LLVM would optimize our functions away.
+void BpfBytecode::fixupBTF(BPFfeature &feature)
+{
+  if (!hasSection(".BTF"))
+    return;
```
Comment (jordalgo) [inline src/bpfbytecode.cpp:86]: Should there be an error log or throw here?

Comment (viktormalik) [reply src/bpfbytecode.cpp:86]: I don't think so. If there's no BTF, there's nothing to fixup. While this wouldn't happen now, we may want to have an option not to generate BTF in future. If BTF is not available while it should be, we'll catch that in other places.

File: src/bpfbytecode.cpp [hunk 2]
```diff
@@ -25,4 +26,89 @@ const std::vector<uint8_t> &BpfBytecode::getSection(
...
+// There are cases when BTF generated by LLVM needs to be patched. This is
+// normally done by libbpf but only when loading via bpf_object is used. We're
+// currently using direct loading using bpf_btf_load and bpf_prog_load so we
+// need to mimic libbpf's behavior and do the patching manually.
+// This should go away once we move to bpf_object-based loading.
+//
+// Transformations done:
+// - If running on a kernel not supporting BTF func entries with BTF_FUNC_GLOBAL
+//   linkage, change the linkage type to 0. We cannot do this directly in
+//   codegen b/c LLVM would optimize our functions away.
```
[the remark this answers is not in the document]
Comment (viktormalik) [reply src/bpfbytecode.cpp:82]: I'm not sure, from my experience with LLVM, it's quite complicated and it could be necessary to turn off other optimizations, too (which we don't want).

File: src/bpfbytecode.cpp [hunk 3]
```diff
@@ -25,4 +26,89 @@ const std::vector<uint8_t> &BpfBytecode::getSection(
...
+    default:
+      return -EINVAL;
+  }
+}
+
+// There are cases when BTF generated by LLVM needs to be patched. This is
+// normally done by libbpf but only when loading via bpf_object is used. We're
+// currently using direct loading using bpf_btf_load and bpf_prog_load so we
+// need to mimic libbpf's behavior and do the patching manually.
+// This should go away once we move to bpf_object-based loading.
```
[the remark this answers is not in the document]
Comment (viktormalik) [reply src/bpfbytecode.cpp:77]: Good point, I added it as a new point to the description of #2334.

File: src/bpfbytecode.cpp (hunk 1 above)
Comment (jordalgo) [reply src/bpfbytecode.cpp:86]: Ah ok, I had thought this was just a validation check.

File: CHANGELOG.md [hunk 4]
```diff
@@ -49,6 +49,8 @@ and this project adheres to
   - [#2914](https://github.com/iovisor/bpftrace/pull/2914)
 - Fix uprobe attachment across container boundary
   - [#2662](https://github.com/iovisor/bpftrace/pull/2662)
+- Fixup generated BTF for older kernels
```
Comment (jordalgo) [inline CHANGELOG.md:52]: super nit
```suggestion
- Fix generated BTF for older kernels
```

**Review by jordalgo — COMMENTED** [review]
Code looks good but someone with more btf experience should have a look.

File: CHANGELOG.md (hunk 4 above)
Comment (viktormalik) [reply CHANGELOG.md:52]: Sure, why not.

**Review by ajor — APPROVED** [review]
Looks good to me!

**Comment by viktormalik** [comment]
I was able to reproduce the issue on 5.4.266 kernel and confirm that this fix works. So, I'll go ahead and merge this as it's blocking me on other work.

**Comment by xiaoqing-wei** [comment]
> @xiaoqing-wei @the-prachi do you think you'd be able to test this fix on your setup? Unfortunately, we don't build static binaries for PRs but you could build it yourself by running `nix build .#appimage` with this PR checked out.
> 
> I was able to test this on my local reproducer of #2913 but would like to have a confirmation that it fixes the issue.


I saw there's a new tagged build and it's working for me.

https://github.com/iovisor/bpftrace/releases/download/v0.20.0/binary_tools_man-bundle.tar.xz
