### PR TITLE
Reuse `cat` and `system` ID when expanding probes

### LINKED ISSUE #957: Crash when attaching a kprobe
Minimal reproducer:

```
bpftrace -e 'tracepoint:syscalls:sys_enter_open,tracepoint:syscalls:sys_enter_openat { if (str(args->filename) == "") { cat(""); } }'
```

*  With only 1 tracepoint it doesn't reproduce.
* If I separate into 2 different probes it doesn't reproduce.
* Without the conditional it doesn't reproduce. 
* Without the `cat()` it doesn't reproduce.

The backtrace is:

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f76d3124935 in __GI_abort () at abort.c:90
#2  0x00007f76d3ad3395 in __gnu_cxx::__verbose_terminate_handler () at ../../.././libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007f76d3ad1016 in __cxxabiv1::__terminate (handler=<optimized out>) at ../../.././libstdc++-v3/libsupc++/eh_terminate.cc:47
#4  0x00007f76d3ad1061 in std::terminate () at ../../.././libstdc++-v3/libsupc++/eh_terminate.cc:57
#5  0x00007f76d3ad133b in __cxxabiv1::__cxa_throw (obj=obj@entry=0x473fa80, tinfo=0x7f76d3dc9a58 <typeinfo for std::out_of_range>, dest=0x7f76d3aefe20 <std::out_of_range::~out_of_range()>) at ../../.././libstdc++-v3/libsupc++/eh_throw.cc:93
#6  0x00007f76d3b07ea7 in std::__throw_out_of_range_fmt (__fmt=<optimized out>) at ../../../.././libstdc++-v3/src/c++11/functexcept.cc:96
#7  0x00000000009bd663 in bpftrace::ast::CodegenLLVM::createFormatStringCall(bpftrace::ast::Call&, int&, std::vector<std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<bpftrace::Field, std::allocator<bpftrace::Field> > >, std::allocator<std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<bpftrace::Field, std::allocator<bpftrace::Field> > > > >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bpftrace::AsyncAction) ()
#8  0x00000000009bf95a in bpftrace::ast::CodegenLLVM::visit(bpftrace::ast::Call&) ()
#9  0x00000000009b9108 in bpftrace::ast::CodegenLLVM::visit(bpftrace::ast::If&) ()
#10 0x00000000009c2955 in bpftrace::ast::CodegenLLVM::visit(bpftrace::ast::Probe&) ()
#11 0x00000000009b7370 in bpftrace::ast::CodegenLLVM::visit(bpftrace::ast::Program&) ()
#12 0x00000000009c466f in bpftrace::ast::CodegenLLVM::compile(bpftrace::DebugLevel, std::ostream&) ()
#13 0x00000000008e650f in main ()
```

### PR DESCRIPTION
**Pull request by fbs**
As `system` and `cat` work basically the same as `printf` we need to use
the same `id` reuse trick.

trigger:

```
tracepoint:syscalls:sys_enter_open,tracepoint:syscalls:sys_enter_openat
{
  if (str(args->filename) == "") {
    cat("");
  }
}
```

Results in:

```
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 1) >= this->size() (which is 1)
Aborted
```

Closes #957

### CODE REVIEW

**Comment by javierhonduco** [comment]
Thanks!! :)

File: src/ast/codegen_llvm.cpp [hunk 1]
```diff
@@ -1286,6 +1286,8 @@ void CodegenLLVM::visit(Probe &probe)
      * can restore it for the next pass (printf_id_, time_id_).
      */
     int starting_printf_id_ = printf_id_;
+    int starting_cat_id_ = cat_id_;
+    int starting_system_id_ = system_id_;
     int starting_time_id_ = time_id_;
     int starting_join_id_ = join_id_;
```
Comment (danobi) [inline src/ast/codegen_llvm.cpp]: Can you change these local variables to not have the trailing `_`?

Was kinda confusing reading this.

**Comment by fbs** [comment]
updated @danobi
