### PR TITLE
Fix attaching to USDT probes with semaphore and USDT runtime tests

### LINKED ISSUE #612: USDT tracing does not set semaphore
TL;DR: USDT probes which make use of a semaphore to detect when probing is enabled are currently broken with the latest changes in `master`.

# Environment

```
$ uname -a
Linux turing 5.0.11-arch1-1-ARCH #1 SMP PREEMPT Thu May 2 19:48:15 UTC 2019 x86_64 GNU/Linux
$ bpftrace --version
bpftrace v0.9-145-ge959
$ pacman -Q bcc
bcc 0.9.0-1
```

# Problem Description

Some USDT probes make use of an optional feature of USDT probing, called "semaphores", in which a `unsigned short` variable placed in a special `.probes` section of the ELF binary is incremented whenever a probe is attached, and decremented when it's detached.  These probes can then check the value of this variable and only execute probing code if it's non-zero.

I'm working on a [Rust crate to bring USDT probing to stable  Rust](https://github.com/anelson/tracers), and due to the way it's implemented each time a probe is hit the Rust code has to `call` into a C++ function, and in some cases do even more work.  So I've implemented this crate to use semaphores to avoid this overhead unless a probe is enabled.

The problem is that `bpftrace` has a bug whereby it increments and then immediately decrements this semaphore, so the code firing the probe never sees a non-zero value and thus never fires the probe.

# Steps to reproduce

I modified the `usdt_test` test program in the `bpftrace` source tree to illustrate this problem.  Here's the code I'm using:

```c
#define _SDT_HAS_SEMAPHORES 1


#define STAP_HAS_SEMAPHORES 1 /* deprecated */

#include <sys/sdt.h>
#include <sys/time.h>
#include <unistd.h>
#include <stdio.h>

__extension__ unsigned short tracetest_testprobe_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes"))) __attribute__ ((visibility ("hidden")));
__extension__ unsigned short tracetest_testprobe2_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes"))) __attribute__ ((visibility ("hidden")));
__extension__ unsigned short tracetest2_testprobe2_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes"))) __attribute__ ((visibility ("hidden")));

static long
myclock() {
  struct timeval tv;
  gettimeofday(&tv, NULL);
  printf("tracetest_testprobe_semaphore: %d\n", tracetest_testprobe_semaphore);
  printf("tracetest_testprobe2_semaphore: %d\n", tracetest_testprobe2_semaphore);
  printf("tracetest2_testprobe2_semaphore: %d\n", tracetest2_testprobe2_semaphore);
  DTRACE_PROBE2(tracetest,  testprobe,  tv.tv_sec, "Hello world");
  DTRACE_PROBE2(tracetest,  testprobe2, tv.tv_sec, "Hello world2");
  DTRACE_PROBE2(tracetest2, testprobe2, tv.tv_sec, "Hello world3");
  return tv.tv_sec;
}

int
main(int argc, char **argv) {
  while(1) {
    usleep(500000);
    myclock();
  }
    return 0;
}
```
You can see I added some `printf` statements and modified the code to run in an infinite loop.  When the probe is not enabled, you see output like this:

```
tracetest_testprobe_semaphore: 0
tracetest_testprobe2_semaphore: 0
tracetest2_testprobe2_semaphore: 0
```

If a probe (let's say `testprobe`) is enabled, you should see this:
```
tracetest_testprobe_semaphore: 1
```

In fact, if I use the `bcc` tool `trace`, that's exactly what happens:

```
$ sudo trace 'u:/home/cornelius/sources/bpftrace/build/tests/testprogs/usdt_test:testprobe' -p $(pidof usdt_test) -T

...
tracetest_testprobe_semaphore: 1
```
But when I try to do the same with `bpftrace`:

```
$ sudo src/bpftrace -e 'usdt::tracetest:testprobe { printf("%s\n", probe); }' -p `pidof usdt_test`
....
tracetest_testprobe_semaphore: 0
```

# Diagnosis

Using `strace` I traced the syscalls that `bpftrace` is making, and I found this bizarre sequence:

```
openat(AT_FDCWD, "/proc/24929/mem", O_RDWR) = 13                                                                    
...
write(13, "\1\0", 2)                    = 2
... (About half a dozen syscalls later)
openat(AT_FDCWD, "/proc/24929/mem", O_RDWR) = 13
...
write(13, "\0\0", 2)                    = 2
```

In other words, `bpftrace` is reaching into the `usdt_test` process memory, correctly setting the semaphore to `0x0100`, and then quickly thereafter setting it back to `0x0000` again.

After impugning the reputation of `bpftrace`'s mother most impolitely, I calmed down and decided to use `bpftrace` itself to gather more data.

Though I reproduced this problem with the versions packaged in the Arch linux repos, I then built both `bcc` and `bpftrace` from source using the latest `master`, in debug mode.  Then I used this (probably not very well written) eBPF program:

```ebpf
tracepoint:syscalls:sys_enter_openat {
 if (str(args->filename) == "/proc/17904/mem") {
     @is_interesting[tid] = 1
 }
}

tracepoint:syscalls:sys_exit_openat /@is_interesting[tid]/ {
 @fd[args->ret] = 1;
 delete(@is_interesting[tid]);
}

tracepoint:syscalls:sys_enter_write {
 if (@fd[args->fd]) {
     printf("Writer:\n%s\n", ustack());
 }
}

tracepoint:syscalls:sys_enter_close {
    delete(@fd[args->fd]);
}
```

It dumps the user stack trace of the calling process whenever it tries to write to the process memory of the `usdt_test` process.  This is what it produced on my system:

```

Writer:

        __write+24
        USDT::Probe::enable(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+108
        USDT::Context::enable_probe(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+431
        bcc_usdt_enable_fully_specified_probe+228
        bpftrace::AttachedProbe::attach_usdt(int)+794
        bpftrace::AttachedProbe::AttachedProbe(bpftrace::Probe&, std::tuple<unsigned char*, unsigned long>, int)+143
        std::_MakeUniq<bpftrace::AttachedProbe>::__single_object std::make_unique<bpftrace::AttachedProbe, bpftrace::Probe&, std::tuple<unsigned char*, unsigned long> const&, int&>(bpftrace::Probe&, std::tuple<unsigned char*, unsigned long> const&, int&)+137
        bpftrace::BPFtrace::attach_probe(bpftrace::Probe&, bpftrace::BpfOrc const&)+761
        bpftrace::BPFtrace::run(std::unique_ptr<bpftrace::BpfOrc, std::default_delete<bpftrace::BpfOrc> >)+794
        main+4312
        __libc_start_main+243
        0x5541f689495641d7

Writer:

        __write+24
        USDT::Probe::disable()+146
        USDT::Context::~Context()+193
        bcc_usdt_close+45
        bpftrace::AttachedProbe::attach_usdt(int)+1254
        bpftrace::AttachedProbe::AttachedProbe(bpftrace::Probe&, std::tuple<unsigned char*, unsigned long>, int)+143
        std::_MakeUniq<bpftrace::AttachedProbe>::__single_object std::make_unique<bpftrace::AttachedProbe, bpftrace::Probe&, std::tuple<unsigned char*, unsigned long> const&, int&>(bpftrace::Probe&, std::tuple<unsigned char*, unsigned long> const&, int&)+137
        bpftrace::BPFtrace::attach_probe(bpftrace::Probe&, bpftrace::BpfOrc const&)+761
        bpftrace::BPFtrace::run(std::unique_ptr<bpftrace::BpfOrc, std::default_delete<bpftrace::BpfOrc> >)+794
        main+4312
        __libc_start_main+243
        0x5541f689495641d7
```

Note this is the same pattern from the `strace` output: The first one is the correct on, enabling the probe, and the second one right after it is disabling it again.  Note the call to `bcc_usdt_close`.  That can't be right...

I did a bit of `git blame`ing and found [this commit from @dalehamel  about a month ago](https://github.com/iovisor/bpftrace/commit/ca814921f6db19b350b57d8e997507acf8cd0739#diff-ebadb41111e6bed6f2d85796dae909f1):

If I'm reading that right, this `bcc_usdt_close()` call was added.  When that call happens, the `bcc` library decrements the semaphore again, thus causing this defect.

# Fix

I assume this `bcc_usdt_close()` call was added for some reason.  I'm hoping @dalehamel  sees this and can comment.

Going forward I would propose that another testprog be added, something like the modification I made to `usdt_test.c`, to ensure USDT probes which use semaphores are exercised properly as part of the automated testing regime.

### PR DESCRIPTION
**Pull request by dalehamel**
This should fix #612 which @anelson correctly identified the issue in his detailed bug report.

I erroneously added code to close the USDT context in an inappropriate spot, which broke the semaphore handling functionality.

I've added a runtime test that will prevent this issue in the future, as well as fixed an issue with runtime tests for USDT that was introduced in #610 where the macro wasn't actually defined, which caused runtime tests to fail even on platforms with `sys/sdt.h` (cc @jasonk000)

@ajor can you take a look please?

### CODE REVIEW

**Comment by dalehamel** [comment]
Just noticed that @mmarchini has a draft PR (#690) that fixes the issue from #610. i'll adopt his code from there to avoid a conflict

File: tests/testprogs/usdt_semaphore_test.c [hunk 1]
```diff
@@ -0,0 +1,34 @@
+#define _SDT_HAS_SEMAPHORES 1
```
Comment (dalehamel) [inline tests/testprogs/usdt_semaphore_test.c]: I made this a separate test program, as this macro forces *all* probes to have a semaphore, and we want to be able to test both semaphore and non-semaphore cases.

**Comment by danobi** [comment]
I merged the other PR. Could you please rebase?

**Comment by mmarchini** [comment]
I'm ok with landing this, but I think we should open a follow-up issue to properly close `ctx`.

**Comment by dalehamel** [comment]
@mmarchini I agree. I’ll rebase, file the issue, and get started on fixing the dangling context. I have an idea of how to properly solve that properly.

**Comment by javierhonduco** [comment]
LGTM! Thanks for fixing this @dalehamel, we also hit this problem with our Python probes (and nice to see you around btw, long time no see! 😀)

**Comment by dalehamel** [comment]
@mmarchini I've rebased, fixed-up the tests, and tried to make the runtime tests here follow your established idioms from #690.

I've filed #744 to properly deal with the USDT context, I'll take a look at that issue soon.
