### PR TITLE
Fix interval probe attachment when CPU 0 is offline (#4966)

### LINKED ISSUE #4966: interval probe fails when CPU 0 is offline (hardcoded cpu=0 in AttachedIntervalProbe)
### Describe the bug
The interval probe type attaches to perf_event_open with a hardcoded cpu index of 0. This causes the probe attachment to fail on systems where CPU 0 is offline (e.g., embedded devices using CPU hotplug/isolation), hindering the use of interval probes in such environments.

### Reproduction Steps
On a Linux system (arm64/x86), offline CPU 0:
echo 0 > /sys/devices/system/cpu/cpu0/online
Run a simple interval probe:
bpftrace -e 'interval:s:1 { print("tick"); }'

Image

#### Expected Behavior
The probe should attach successfully to an available online CPU (e.g., the first online CPU) or all online CPUs, similar to how profile or software probes behave.

#### Actual Behavior
The tool fails to attach with an error, because perf_event_open returns ENODEV (or similar) when requested for an offline CPU.

### Additional context
I checked the source code in src/attached_probe.cpp(latest master). The AttachedIntervalProbe::make function hardcodes cpu = 0:
`// src/attached_probe.cpp
Result<std::unique_ptr<AttachedIntervalProbe>> AttachedIntervalProbe::make(...) {
  int cpu = 0; // <--- Hardcoded
  // ...
  int perf_event_fd = open_perf_event(..., cpu, ...);
}`

In contrast, 
AttachedProfileProbe
 in the same file correctly uses get_online_cpus() to handle this scenario.

### PR DESCRIPTION
**Pull request by nanshuaibo**
This PR addresses the issue where attaching `interval` probes fails when CPU 0 is offline (or hot-unplugged).

Previously, `AttachedIntervalProbe::make` hardcoded `cpu=0` when creating the perf event. This caused [open_perf_event](cci:1://file:///data/8797/nhlos/lagvm/LINUX/android/external/bpftrace/src/attached_probe.cpp:856:0-884:1) to fail if CPU 0 was not available.

This change updates it to utilize `util::get_online_cpus()` to dynamically select the first available online CPU, ensuring the probe can be attached successfully regardless of CPU 0's status. All other online CPUs are then looped over correctly as before.

Fixes #4966.

##### Checklist

- [ ] Language changes are updated in `docs/language.md`, `docs/stdlib.md`, or `man/adoc/bpftrace.adoc` (N/A)
- [x] User-visible and non-trivial changes updated in `CHANGELOG.md`
- [x] The new behaviour is covered by tests

### CODE REVIEW

**Comment by jordalgo** [comment]
@nanshuaibo Thanks for the PR. This is a good first step. Do you want to add the logic for the other probes where we use cpu 0 by default?

Also, and perhaps this can be a follow-up PR, how about adding some monitoring so we know if the chosen CPU goes offline as mentioned here: https://github.com/bpftrace/bpftrace/issues/4966#issuecomment-3820847749

BTW, the DCO check is failing because you need a "signed-off" in your commit message (see others for examples)

**Comment by nanshuaibo** [comment]
Thanks for the review @jordalgo！ 
I've checked all probe types in [attached_probe.cpp](https://github.com/bpftrace/bpftrace/blob/master/src/attached_probe.cpp), and `AttachedIntervalProbe` is the only one that hardcodes cpu=0. The others (profile, software, hardware, watchpoint) already correctly use util::get_online_cpus(). 
I'll fix the DCO check shortly. 
Regarding the monitoring suggestion — that's a great idea! I'd be happy to work on a follow-up PR for that.

**Comment by jordalgo** [comment]
> AttachedIntervalProbe is the only one that hardcodes cpu=0

Ah my bad. If you want to separate that one commit out, we can merge that. I see you already started working on the monitor, let me know if you just want to continue that work on this PR.

File: src/util/perf_event_monitor.h [hunk 1]
```diff
@@ -0,0 +1,50 @@
+#pragma once
+
+#include <atomic>
+#include <mutex>
+#include <set>
+#include <thread>
+
+namespace bpftrace::util {
+
+// PerfEventMonitor watches for CPU hotplug events using Netlink uevents.
```
Comment (amscanne) [inline src/util/perf_event_monitor.h]: The mechanism is uses is netlink, but logically this is just a class for monitoring CPU hotplug events. Can we just call it "CPUMonitor" something similar? (Same for the filename, e.g. cpu_monitor.{h|cpp}).

Then you can call the methods just `register(cpu)`, etc.

File: src/util/perf_event_monitor.h [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+//
+// Usage:
+//   auto &monitor = PerfEventMonitor::instance();
+//   monitor.register_cpu(cpu);
+//   monitor.start();
+//   ...
+//   monitor.stop();
+class PerfEventMonitor {
+public:
+  static PerfEventMonitor &instance();
```
Comment (amscanne) [inline src/util/perf_event_monitor.h]: I'm not sure about the static singleton. Can we just plumb this through where it is needed in the probes? E.g. we could even have a "required_cpus" field or something for the attached probes, which would be read and set in the main monitoring loop. In general I think it is desirable to avoid hidden side-effects.

(Avoiding the singleton here always simplifies the whole lifecycle of the class. See the comment below.)

File: src/util/perf_event_monitor.h [hunk 3]
```diff
@@ -0,0 +1,50 @@
...
+
+  PerfEventMonitor(const PerfEventMonitor &) = delete;
+  PerfEventMonitor &operator=(const PerfEventMonitor &) = delete;
+
+  void register_cpu(int cpu);
+  void start();
+  void stop();
+  void reset();
```
Comment (amscanne) [inline src/util/perf_event_monitor.h]: Can you just bound these to the lifecycle of the object? E.g. make the `CPUMonitor` an RAII-style class and you just register for events, and it will emit to a specific log stream.

```
auto monitor = CPUMonitor(std::cerr);
for (const auto &probe : probes) {
   for (const auto &cpu : probe.required_cpus) {
       monitor.register(cpu);
   }
}

... // let the probes run

// On scope exit, the monitor will automatically signal and join the monitor thread
```

**Review by amscanne — COMMENTED** [review]
The monitoring is neat, and the point fix is good. I've left some comments on the structure for the monitoring.

Longer term, if you're interested, we could also fix the "first CPU" assignment. There are a few options to consider:
- Looking at the full set of attachable CPUs, and smearing the intervals across them
- Randomizing the choice, allowing for an explicit override from the command line
- Looking for the least busy CPU, also allowing for an explicit override from the command line

**Comment by nanshuaibo** [comment]
> > AttachedIntervalProbe is the only one that hardcodes cpu=0
> 
> Ah my bad. If you want to separate that one commit out, we can merge that. I see you already started working on the monitor, let me know if you just want to continue that work on this PR.

Thanks for the suggestion! I've removed the monitoring commit from this PR as discussed. Now this PR only contains the fix for the hardcoded cpu=0 issue.

**Comment by nanshuaibo** [comment]
> The monitoring is neat, and the point fix is good. I've left some comments on the structure for the monitoring.
> 
> Longer term, if you're interested, we could also fix the "first CPU" assignment. There are a few options to consider:
> 
> * Looking at the full set of attachable CPUs, and smearing the intervals across them
> * Randomizing the choice, allowing for an explicit override from the command line
> * Looking for the least busy CPU, also allowing for an explicit override from the command line

Thanks for your review and suggestions!

I've split the monitoring logic into a separate branch to keep this PR focused on the point fix. I'll address your comments (like renaming to CPUMonitor and using RAII style) in a follow-up PR.

Regarding the "first CPU" assignment distribution, I’ll keep your suggestion in mind and might look into that as a future improvement.

**Comment by jordalgo** [comment]
@nanshuaibo Code looks good. I forgot to mention it before but can you add a change log entry in the "Fixed" section?

**Review by amscanne — APPROVED** [review]

**Comment by nanshuaibo** [comment]
> @nanshuaibo Code looks good. I forgot to mention it before but can you add a change log entry in the "Fixed" section?

@jordalgo  Done. Added the changelog entry

File: CHANGELOG.md [hunk 4]
```diff
@@ -86,6 +84,8 @@ and this project adheres to
 - Drop support for LLVM 16
   - [#4534](https://github.com/bpftrace/bpftrace/pull/4534)
 #### Fixed
+- Fix interval probe attachment when CPU 0 is offline
+  - [#4966](https://github.com/bpftrace/bpftrace/pull/4966)
```
Comment (jordalgo) [inline CHANGELOG.md]: This should be 4987 right?

Comment (nanshuaibo) [reply CHANGELOG.md]: Ah, you are right. It was a typo. Fixed in the latest commit.
