### PR TITLE
Attach watchpoints to all existing threads

### LINKED ISSUE #826: Memory watchpoint does not work with threaded targets
Looks like `perf_event_open` does not work if applications use threads. It seems like only the main TID (ie the PID) is traced:

```
$ sudo ./build/src/bpftrace ~/watchpoint.bt -c "/home/dlxu/scratch/bpftrace/mmap_addr/a.out 'pthread on'"
Attaching 1 probe...
Mapped 2097152 bytes at 268435456 (0x10000000)
^C

$  ~/dev/bpftrace git:(master) sudo ./build/src/bpftrace ~/watchpoint.bt -c "/home/dlxu/scratch/bpftrace/mmap_addr/a.out"
Attaching 1 probe...
Mapped 2097152 bytes at 268435456 (0x10000000)
hit!
hit!
hit!
hit!
hit!
hit!
^C

$ cat /home/dlxu/scratch/bpftrace/main.cpp
at /home/dlxu/scratch/bpftrace/mmap_addr/main.cpp
#include <cstdint>
#include <stdio.h>
#include <sys/mman.h>
#include <thread>
#include <unistd.h>
#include <pthread.h>

using namespace std::chrono_literals;

void* work(void* arg) {
  void* addr = ::mmap(
      reinterpret_cast<void*>(0x10000000),
      2 << 20,
      PROT_READ | PROT_WRITE,
      MAP_PRIVATE | MAP_ANONYMOUS,
      -1,
      0);

  if (addr < 0) {
    ::perror("mmap");
    return nullptr;
  }

  printf("Mapped %d bytes at %d (%p)\n", 2 << 20, addr, addr);

  uint8_t count = 0;
  while (count < 20) {
    *reinterpret_cast<uint8_t*>(addr) = count++;
    std::this_thread::sleep_for(1s);
  }

  return nullptr;
}

int main(int argc, char** argv) {
  if (argc > 1) {
    pthread_t tid;
    if (::pthread_create(&tid, nullptr, work, 0)) {
      ::perror("pthread_create");
    }

    if (::pthread_join(tid, nullptr)) {
      ::perror("pthread_join");
    }
  } else {
    work(nullptr);
  }

  ::printf("Exiting...\n");
  return 0;
}
```

Will possibly require a kernel change. Looking into it with @yonghong-song

### PR DESCRIPTION
**Pull request by tnovak**
When attaching a watchpoint probe to a specific process via `-p`, we create just one perf event for that pid and set `attr.inherit` to 1. This is insufficient: it causes the probe to only be attached to the main thread (`tid == pid`) and those created by the main thread after attaching, but not to any of the other existing threads.

Fix this by enumerating all threads of the process via procfs and creating a separate perf event for each thread.

This closes #826.

##### Checklist

- [ ] Language changes are updated in `docs/language.md`, `docs/stdlib.md`, or `man/adoc/bpftrace.adoc`
- [ ] User-visible and non-trivial changes updated in `CHANGELOG.md`
- [ ] The new behaviour is covered by tests

### CODE REVIEW

**Comment by tnovak** [comment]
> [...] creating a separate perf event for each thread

We'd probably want to do this for other probe types as well (I can take a stab at this in a separate PR), but it's arguably most important for watchpoints since the address is likely specific to the process being monitored.

A workaround is to not use `-p` and filter via `/pid == <X>/`

File: tests/runtime/watchpoint [hunk 1]
```diff
@@ -25,3 +25,11 @@ EXPECT hit!
 # Not all archs support mmap to our specific address, so be conservative here.
 # See 08a47afa ("Fixing absolute address test issue across platforms")
 ARCH x86_64
+
+# Attaches a watchpoint probe to an existing multi-threaded process. Waits a bit before running
+# bpftrace to allow the test program to start the thread that triggers the watchpoint.
+NAME watchpoint - existing thread
```
Comment (jordalgo) [inline tests/runtime/watchpoint:31]: nit: I feel like this test and the one above should be a pair, e.g. "watchpoint - existing thread" and "watchpoint - created thread" and perhaps the test program itself should bake in a sleep before it creates a thread (for the latter test).

File: src/util/system.cpp [hunk 2]
```diff
@@ -289,4 +292,28 @@ Result<uint64_t> get_available_mem_kb()
...
+  char task_path[64];
+  snprintf(task_path, sizeof(task_path), "/proc/%d/task", pid);
+
+  std::unique_ptr<DIR, int (*)(DIR *)> dir(opendir(task_path), &closedir);
+  if (!dir) {
+    return make_error<SystemError>("Unable to open " + std::string(task_path));
+  }
+
+  struct dirent *dent;
+  while ((dent = readdir(dir.get()))) {
```
Comment (jordalgo) [inline src/util/system.cpp]: nit: in other parts of the codebase `std::filesystem::directory_iterator` is used

File: src/attached_probe.cpp [hunk 3]
```diff
@@ -1417,56 +1418,58 @@ Result<std::unique_ptr<AttachedWatchpointProbe>> AttachedWatchpointProbe::make(
...
+      // We copy paste the code from bcc's bpf_attach_perf_event_raw here
+      // because we need to know the exact error codes (and also we don't
+      // want bcc's noisy error messages).
+      int perf_event_fd = syscall(
+          __NR_perf_event_open, &attr, tid, cpu, -1, PERF_FLAG_FD_CLOEXEC);
+      if (perf_event_fd < 0) {
+        if (errno == ENOSPC)
+          err_msg = "No more HW registers left";
+
+        LOG(V1) << "Failed to create a perf event for cpu " << cpu << " tid "
```
Comment (jordalgo) [inline src/attached_probe.cpp]: Is this too noisy to be a `LOG(WARNING)` ?

**Comment by jordalgo** [comment]
> A workaround is to not use -p and filter via /pid == <X>/

Yeah, this sounds like the most reasonable approach considering the limitations of perf_event_open

File: src/attached_probe.cpp (hunk 3 above)
Comment (tnovak) [reply src/attached_probe.cpp]: I debated whether to use `WARNING` or even leave out the log entirely. It shouldn't be too noisy in practice -- I was mostly concerned about it being misleading in the non-error case where some threads have exited between `get_process_tids()` and `perf_event_open()`.

Looks like `perf` does log a warning in that case ([evsel.c](https://github.com/torvalds/linux/blob/8a30aeb0d1b4e4aaf7f7bae72f20f2ae75385ccb/tools/perf/util/evsel.c#L2230)) so we might as well?

File: tests/testprogs/watchpoint_exec.c [hunk 4]
```diff
@@ -27,6 +27,7 @@ int main()
   memcpy(addr, insns, sizeof(insns));
   void (*func)(void);
   func = addr;
+  sleep(1); // wait a bit for bpftrace to attach
```
Comment (jordalgo) [inline tests/testprogs/watchpoint_exec.c:30]: What is this change for?

Comment (tnovak) [reply tests/testprogs/watchpoint_exec.c:30]: The "watchpoint.execution breakpoint" runtime test sporadically failed on my system (around 5% of the time or so) without it because the test program would call `func()` before bpftrace had a chance to attach.  This makes the race much less likely to occur.

I can split it out into a separate patch if you'd prefer that.

Comment (jordalgo) [reply tests/testprogs/watchpoint_exec.c:30]: Nm, I guess this can address possible flakyness

Comment (jordalgo) [reply tests/testprogs/watchpoint_exec.c:30]: Ha - ok, I assumed right 😄
