### PR TITLE
Cast LNOT result

### LINKED ISSUE #1223: LLVM SEGV (maybe related to LNOT)
This causes SEGV for some reason.

```
% sudo ./src/bpftrace -e 'k:f { $a = !nsecs; @ = $a + nsecs;}'
AddressSanitizer:DEADLYSIGNAL
=================================================================
==27358==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000018 (pc 0x7fed0a6bfdc4 bp 0x621000049188 sp 0x7ffdfa414ee0 T0)
==27358==The signal is caused by a READ memory access.
==27358==Hint: address points to the zero page.
    #0 0x7fed0a6bfdc4 in llvm::SelectionDAG::getNode(unsigned int, llvm::SDLoc const&, llvm::EVT, llvm::SDValue, llvm::SDValue, llvm::SDNodeFlags) (/usr/lib/llvm-9/lib/libLL
VM-9.so.1+0xfbadc4)
    #1 0x7fed0a6141e3  (/usr/lib/llvm-9/lib/libLLVM-9.so.1+0xf0f1e3)
    #2 0x7fed0a60f08d  (/usr/lib/llvm-9/lib/libLLVM-9.so.1+0xf0a08d)
    #3 0x7fed0a62d0ec  (/usr/lib/llvm-9/lib/libLLVM-9.so.1+0xf280ec)
    #4 0x7fed0a6314e9 in llvm::SelectionDAG::LegalizeTypes() (/usr/lib/llvm-9/lib/libLLVM-9.so.1+0xf2c4e9)
    #5 0x7fed0a6fb7a5 in llvm::SelectionDAGISel::CodeGenAndEmitDAG() (/usr/lib/llvm-9/lib/libLLVM-9.so.1+0xff67a5)
    #6 0x7fed0a6fb296 in llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) (/usr/lib/llvm-9/lib/libLLVM-9.so.1+0xff6296)
    #7 0x7fed0a6f8c85 in llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) (/usr/lib/llvm-9/lib/libLLVM-9.so.1+0xff3c85)
    #8 0x7fed0a3c5987 in llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (/usr/lib/llvm-9/lib/libLLVM-9.so.1+0xcc0987)
    #9 0x7fed0a23c245 in llvm::FPPassManager::runOnFunction(llvm::Function&) (/usr/lib/llvm-9/lib/libLLVM-9.so.1+0xb37245)
    #10 0x7fed0a23c4f2 in llvm::FPPassManager::runOnModule(llvm::Module&) (/usr/lib/llvm-9/lib/libLLVM-9.so.1+0xb374f2)
    #11 0x7fed0a23c99f in llvm::legacy::PassManagerImpl::run(llvm::Module&) (/usr/lib/llvm-9/lib/libLLVM-9.so.1+0xb3799f)
    #12 0x7fed0b25c7a2 in llvm::orc::SimpleCompiler::operator()(llvm::Module&) (/usr/lib/llvm-9/lib/libLLVM-9.so.1+0x1b577a2)
    #13 0x89e9da in llvm::orc::LegacyIRCompileLayer<llvm::orc::LegacyRTDyldObjectLinkingLayer, llvm::orc::SimpleCompiler>::addModule(unsigned long, std::unique_ptr<llvm::Mod
ule, std::default_delete<llvm::Module> >) /usr/lib/llvm-9/include/llvm/ExecutionEngine/Orc/IRCompileLayer.h:93:54
    #14 0x89e7ca in bpftrace::BpfOrc::addModule(std::unique_ptr<llvm::Module, std::default_delete<llvm::Module> >) /home/ubuntu/work/bpftrace/bpftrace/build_asan/../src/bpfo
rc.h:147:27
    #15 0x89ab1b in bpftrace::BpfOrc::compileModule(std::unique_ptr<llvm::Module, std::default_delete<llvm::Module> >) /home/ubuntu/work/bpftrace/bpftrace/build_asan/../src/
bpforc.h:140:14
    #16 0x896cd8 in bpftrace::ast::CodegenLLVM::compile(bpftrace::DebugLevel, std::ostream&) /home/ubuntu/work/bpftrace/bpftrace/build_asan/../src/ast/codegen_llvm.cpp:2051:
11
    #17 0x80f89c in main /home/ubuntu/work/bpftrace/bpftrace/build_asan/../src/main.cpp:589:22
    #18 0x7fed06307b96 in __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:310
    #19 0x5c1e39 in _start (/home/ubuntu/work/bpftrace/bpftrace/build_asan/src/bpftrace+0x5c1e39)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/usr/lib/llvm-9/lib/libLLVM-9.so.1+0xfbadc4) in llvm::SelectionDAG::getNode(unsigned int, llvm::SDLoc const&, llvm::EVT, llvm::SDValue, llvm
::SDValue, llvm::SDNodeFlags)
==27358==ABORTING
```

I found that the error does not occur when casting a LNOT result to int64.

```
% ./src/bpftrace -e 'k:f { $a = (uint64)!nsecs; @ = $a + nsecs;}'
Attaching 1 probe...
^C
```

-------

LLVM version: 9

### PR DESCRIPTION
**Pull request by mmisono**
CreateICmpEQ() returns 1-bit integer and this can causes typing issues.
Promote a result to the same type of the operand.

Fixes #1223

### CODE REVIEW

File: src/ast/codegen_llvm.cpp [hunk 1]
```diff
@@ -994,8 +994,15 @@ void CodegenLLVM::visit(Unop &unop)
...
-        Value *zero_value = Constant::getNullValue(expr_->getType());
+        auto ty = expr_->getType();
+        Value *zero_value = Constant::getNullValue(ty);
         expr_ = b_.CreateICmpEQ(expr_, zero_value);
+        // CreateICmpEQ() returns 1-bit integer
+        // Cast it to the same type of the operand
+        // Use unsigned extention first, otherwise !0 becomes -1
+        expr_ = b_.CreateIntCast(expr_, ty, false);
+        if (unop.expr->type.is_signed)
+          expr_ = b_.CreateIntCast(expr_, ty, true);
```
Comment (mmisono) [inline src/ast/codegen_llvm.cpp]: I realized that LLVM does not distinguish signed and unsigned, so this is not needed.
