### PR TITLE
Attachpoint parser: improve stoull error messages

### LINKED ISSUE #2680: Bad error message with bad interval probe specification
### What reproduces the bug?
I mistakenly transposed the time unit specifier and the rate in an interval probe definition and the error message returned was decidedly sub-optimal.

```
# bpftrace -e 'interval:5:s{ @[comm] = count();}'
stdin:1:1-13: ERROR: stoull
interval:5:s{ @[comm] = count();}
```

```
### bpftrace --info
# bpftrace --info
System
  OS: Linux 5.12.0-0_fbk14_clang_7533_g0df3a3e4e046 #1 SMP Tue May 2 17:02:10 PDT 2023
  Arch: x86_64

Build
  version: v0.18.0
  LLVM: 12.0.20210610
  unsafe probe: no
  bfd: yes
  libdw (DWARF support): yes

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: yes
  probe_read_user_str: yes
  probe_read_kernel: yes
  probe_read_kernel_str: yes
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: yes
  get_boot_ns: yes
  dpath: yes
  skboutput: yes

Kernel features
  Instruction limit: 1000000
  Loop support: yes
  btf: yes
  module btf: yes
  map batch: yes
  uprobe refcount (depends on Build:bcc bpf_attach_uprobe refcount): yes

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes
  ringbuf: yes

Probe types
  kprobe: yes
  tracepoint: yes
  perf_event: yes
  kfunc: yes
  kprobe_multi: yes
  raw_tp_special: yes
  iter: yes

### PR DESCRIPTION
**Pull request by viktormalik**
There's a number of probe types that expect a number as one of their arguments. We use our own parser to convert a string to an integer, however, when it fails, the error message is not very nice:

    # bpftrace -e 'interval:5:s{ @[comm] = count();}'
    stdin:1:1-13: ERROR: stoull
    interval:5:s{ @[comm] = count();}

Provide better messages for all places where stoull/stoll may fail in AttachPointParser:

    # bpftrace -e 'interval:5:s{ @[comm] = count();}'
    stdin:1:1-13: ERROR: stoull
    invalid rate of interval probe
    interval:5:s{ @[comm] = count();}

Fixes #2680.

##### Checklist

- [ ] Language changes are updated in `man/adoc/bpftrace.adoc` and if needed in `docs/reference_guide.md`
- [ ] User-visible and non-trivial changes updated in `CHANGELOG.md`
- [ ] The new behaviour is covered by tests

### CODE REVIEW

File: src/ast/attachpoint_parser.cpp [hunk 1]
```diff
@@ -550,7 +556,10 @@ AttachPointParser::State AttachPointParser::profile_parser()
 
   auto res = stoull(parts_[2]);
   if (!res)
+  {
+    errs_ << "invalid rate of " << ap_->provider << " probe";
```
Comment (danobi) [inline src/ast/attachpoint_parser.cpp:560]: Nit: capitalize `invalid`? Or lowercase the ones above. Same for a few below

**Review by danobi — APPROVED** [review]
