### PR TITLE
Do not try to load bpf program with unknown kernel version

### LINKED ISSUE #506: no error log printed on systems without /usr directory
Android is a quite hostile environment and it has no /usr directory which makes [kernel_version](https://github.com/iovisor/bpftrace/blob/master/src/attached_probe.cpp#L295) fail during 3rd attempt to load a bpf program, in which case we end up with no info what went wrong. Here is a detailed description of the problem I run into:
1. I run bpftrace script which depends on a helper function not provided by my kernel
2. [first two attempts](https://github.com/iovisor/bpftrace/blob/master/src/attached_probe.cpp#L336) to load bpf program fail with useful hints logged to log_buf
3. during 3rd attempt [kernel_version](https://github.com/iovisor/bpftrace/blob/master/src/attached_probe.cpp#L295) returns 0 due to missing "/usr/include/linux/version.h" header
4. bpf_prog_load is called with wrong kernel version (0)
5. bpf_prog_load zeroes first byte of the provided log_buf
6. bpf syscall is called
7. kernel does not append anything to the log buffer before returning EINVAL
8. we end up with an empty log_buf even though first two attempts resulted in useful information being logged

I tried to work around this by running with `-d` or `-dd` ([this is what seeded the idea](https://github.com/iovisor/bpftrace/blob/master/src/attached_probe.cpp#L317)) but turns out the execuction terminates [before bpf_prog_load is called](https://github.com/iovisor/bpftrace/blob/master/src/main.cpp#L301).

I ended up adding check for `kernel_version` returning 0 and simply skipping iterations where that happens, although dumping the buffer after each failed iteration also sounds tempting. Please let me know if this is the right approach and it's worth opening a pull request.

### PR DESCRIPTION
**Pull request by michalgr**
Fixes #506 (subsequent calls to bpf_prog_load with kernel version = 0 zeroing
log_buf)

test plan:
1. build bpftrace for android and make sure that I see verifier errors when
using functionality that is not provided by old linux kernel
2. change kernel_version to always return 0 and verify that appropriate error
is written to stderr.

### CODE REVIEW

File: src/attached_probe.cpp [hunk 1]
```diff
@@ -333,15 +334,20 @@ void AttachedProbe::load_prog()
   if (strrchr(name, ':') != NULL)
     namep = strrchr(name, ':') + 1;
 
+  snprintf(log_buf, sizeof(log_buf), "could not determine kernel version");
   for (int attempt=0; attempt<3; attempt++)
   {
+    auto version_of_kernel = kernel_version(attempt);
```
Comment (ajor) [inline src/attached_probe.cpp]: `version_of_kernel` just sounds a bit strange to me - maybe just `version` or some other shorter name

File: src/attached_probe.cpp [hunk 2]
```diff
@@ -62,7 +63,7 @@ bpf_prog_type progtype(ProbeType t)
 
 
 AttachedProbe::AttachedProbe(Probe &probe, std::tuple<uint8_t *, uintptr_t> func)
-  : probe_(probe), func_(func)
+  : probe_(probe), func_(func), progfd_(-1)
```
Comment (ajor) [inline src/attached_probe.cpp]: I think this initialisation would be better somewhere else - if we create a new constructor in the future we could forget to copy this across. Either setting it in the class definition in `attached_probe.h` with a comment, or just before we start the `for..attempt` loop below would work and be safer.

File: src/attached_probe.cpp [hunk 3]
```diff
@@ -333,15 +334,20 @@ void AttachedProbe::load_prog()
   if (strrchr(name, ':') != NULL)
     namep = strrchr(name, ':') + 1;
 
+  snprintf(log_buf, sizeof(log_buf), "could not determine kernel version");
```
Comment (ajor) [inline src/attached_probe.cpp]: Does this error message show up if we don't ever get to try prog_load? This confused me at first so could either do with some refactoring or a comment to clarify what it's for.

**Comment by ajor** [comment]
Sorry, I forgot about this recent-ish change to the Linux kernel: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=6c4fc209fcf9d27efbaa48368773e4d2bfbd59aa

In newer kernels Linux won't do a version check at all, so we shouldn't totally give up if we can't determine what version we're running on, as it might not matter.

File: src/attached_probe.cpp (hunk 3 above)
Comment (michalgr) [reply src/attached_probe.cpp]: yeah, if bcc_prog_load/bpf_prog_load is called at least once it will zero the first byte of the message: https://github.com/iovisor/bcc/blob/master/src/cc/libbpf.c#L509.

Anyway, as you pointed out, it is far from obvious. I'll keep a boolean tracking whether *_prog_load was called at least once and throw exception if not.

**Comment by michalgr** [comment]
I see. Should I just dump the error log after each unsuccessful attempt to call bpf_prog_load ? Or allow zero in the last iteration if previous attempts did not determine kernel version either ?

**Comment by brendangregg** [comment]
thanks, I'll merge, but I'll also do some quick tests to see if there's any needed followups.

**Comment by michalgr** [comment]
Thank you. Please let me know if I need to fix anything.
