### PR TITLE
Fix pointer arithmetics codegen

### LINKED ISSUE #2394: fedora36 Segmentation fault when print ipheader pointer
### What reproduces the bug?
when I run the following command, 
```
bpftrace -e 'kprobe:consume_skb{$skb = (struct sk_buff *)arg0;$iph = ((struct iphdr *) ($skb->head + $skb->network_header));printf("$iph:%p\n",$iph);}'
```
I got a error: Segmentation fault (core dumped);
what I  expect is to print ipheader pointer;

#### gdb backtrace
I use gdb to print the backtrace
```
Thread 1 "bpftrace" received signal SIGSEGV, Segmentation fault.
llvm::SelectionDAG::getNode (this=0x1289250, Opcode=55, DL=..., VT=..., N1=..., N2=..., Flags=...) at /usr/src/debug/llvm-14.0.5-1.fc36.x86_64/lib/CodeGen/SelectionDAG/SelectionDAG.cpp:5650
5650	    bool IsN2C = isConstantIntBuildVectorOrConstantInt(N2);
(gdb) bt
#0  llvm::SelectionDAG::getNode (this=0x1289250, Opcode=55, DL=..., VT=..., N1=..., N2=..., Flags=...)
    at /usr/src/debug/llvm-14.0.5-1.fc36.x86_64/lib/CodeGen/SelectionDAG/SelectionDAG.cpp:5650
#1  0x00007ffff0d4d1df in llvm::DAGTypeLegalizer::PromoteIntRes_SimpleIntBinOp (this=0x7fffffff86f8, N=0x1304b90)
    at /usr/src/debug/llvm-14.0.5-1.fc36.x86_64/lib/CodeGen/SelectionDAG/LegalizeIntegerTypes.cpp:1194
#2  llvm::DAGTypeLegalizer::PromoteIntegerResult (this=0x7fffffff86f8, N=0x1304b90, ResNo=0)
    at /usr/src/debug/llvm-14.0.5-1.fc36.x86_64/lib/CodeGen/SelectionDAG/LegalizeIntegerTypes.cpp:160
#3  0x00007ffff0d79df5 in llvm::DAGTypeLegalizer::run (this=0x7fffffff86f8) at /usr/src/debug/llvm-14.0.5-1.fc36.x86_64/lib/CodeGen/SelectionDAG/LegalizeTypes.cpp:255
#4  llvm::SelectionDAG::LegalizeTypes (this=<optimized out>) at /usr/src/debug/llvm-14.0.5-1.fc36.x86_64/lib/CodeGen/SelectionDAG/LegalizeTypes.cpp:1052
#5  0x00007ffff0e7cf22 in llvm::SelectionDAGISel::CodeGenAndEmitDAG (this=0x12880b0) at /usr/src/debug/llvm-14.0.5-1.fc36.x86_64/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:840
#6  0x00007ffff0e7cd95 in llvm::SelectionDAGISel::SelectBasicBlock (this=0x129fda0, Begin=..., End=..., HadTailCall=<error reading variable: Cannot access memory at address 0x3f>)
    at /usr/src/debug/llvm-14.0.5-1.fc36.x86_64/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:734
#7  0x00007ffff0e7c500 in llvm::SelectionDAGISel::SelectAllBasicBlocks (this=0x12880b0, Fn=...)
    at /usr/src/debug/llvm-14.0.5-1.fc36.x86_64/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:1634
#8  0x00007ffff0e79849 in llvm::SelectionDAGISel::runOnMachineFunction (this=0x12880b0, mf=...) at /usr/src/debug/llvm-14.0.5-1.fc36.x86_64/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:515
#9  0x00007ffff09e55dd in llvm::MachineFunctionPass::runOnFunction (this=0x12880b0, F=...) at /usr/src/debug/llvm-14.0.5-1.fc36.x86_64/lib/CodeGen/MachineFunctionPass.cpp:72
#10 0x00007ffff0777921 in llvm::FPPassManager::runOnFunction (this=0x7fffe80496a0, F=...) at /usr/src/debug/llvm-14.0.5-1.fc36.x86_64/lib/IR/LegacyPassManager.cpp:1434
#11 0x00007ffff077e813 in llvm::FPPassManager::runOnModule (this=0x7fffe80496a0, M=...) at /usr/src/debug/llvm-14.0.5-1.fc36.x86_64/lib/IR/LegacyPassManager.cpp:1480
#12 0x00007ffff0778099 in (anonymous namespace)::MPPassManager::runOnModule (this=0x7fffe80436c0, M=...) at /usr/src/debug/llvm-14.0.5-1.fc36.x86_64/lib/IR/LegacyPassManager.cpp:1549
#13 llvm::legacy::PassManagerImpl::run (this=0x1285000, M=...) at /usr/src/debug/llvm-14.0.5-1.fc36.x86_64/lib/IR/LegacyPassManager.cpp:539
#14 0x00000000006cd92d in bpftrace::ast::CodegenLLVM::emit (this=0x7fffffffa3c0, stream=...) at /home/barry/workspace/dynamic-tracing/ebpf/bpftrace/src/ast/passes/codegen_llvm.cpp:3306
#15 0x00000000006cd9e8 in bpftrace::ast::CodegenLLVM::emit[abi:cxx11]() (this=0x7fffffffa3c0) at /home/barry/workspace/dynamic-tracing/ebpf/bpftrace/src/ast/passes/codegen_llvm.cpp:3315
#16 0x000000000042164d in main (argc=3, argv=0x7fffffffcab8) at /home/barry/workspace/dynamic-tracing/ebpf/bpftrace/src/main.cpp:932
(gdb) 
```

### bpftrace --info
```
System
  OS: Linux 5.19.15-201.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Oct 13 18:58:38 UTC 2022
  Arch: x86_64

Build
  version: v0.16.0-32-gcf34
  LLVM: 14.0.5
  foreach_sym: yes
  unsafe uprobe: no
  bfd: yes
  bcc_usdt_addsem: yes
  bcc bpf_attach_uprobe refcount: yes
  bcc library path resolution: yes
  libbpf btf dump: yes
  libbpf btf dump type decl: yes
  libbpf bpf_prog_load: yes
  libbpf bpf_map_create: yes
  libdw (DWARF support): yes

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: yes
  probe_read_user_str: yes
  probe_read_kernel: yes
  probe_read_kernel_str: yes
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: no
  get_boot_ns: yes
  dpath: yes
  skboutput: no

Kernel features
  Instruction limit: 1000000
  Loop support: yes
  btf: yes
  map batch: yes
  uprobe refcount (depends on Build:bcc bpf_attach_uprobe refcount): yes

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes

Probe types
  kprobe: yes
  tracepoint: yes
  perf_event: yes
  kfunc: yes
  iter:task: yes
  iter:task_file: yes
  kprobe_multi: no
  raw_tp_special: yes
```
### my environment
image

### PR DESCRIPTION
**Pull request by viktormalik**
Codegen for `ptr + X` creates the following instructions:

    %0 = mul sizeof(*ptr), X
    %1 = add ptr, %0

If X is not a 64-bit int, the `mul` will have incompatible operands which will cause a segfault in LLVM (at least in LLVM 14).

This fixes the problem by extending X to 64 bits, if necessary.

Fixes #2394.

##### Checklist

- [ ] Language changes are updated in `man/adoc/bpftrace.adoc` and if needed in `docs/reference_guide.md`
- [x] User-visible and non-trivial changes updated in `CHANGELOG.md`
- [x] The new behaviour is covered by tests

### CODE REVIEW

File: src/ast/passes/codegen_llvm.cpp [hunk 1]
```diff
@@ -1534,10 +1534,14 @@ void CodegenLLVM::binop_ptr(Binop &binop)
...
     // Cannot use GEP here as LLVM doesn't know its a pointer
     bool leftptr = binop.left->type.IsPtrTy();
-    auto &ptr = leftptr ? binop.left->type : binop.right->type;
+    auto &ptr_ty = leftptr ? binop.left->type : binop.right->type;
+    auto &other_ty = leftptr ? binop.right->type : binop.left->type;
     Value *ptr_expr = leftptr ? lhs : rhs;
     Value *other_expr = leftptr ? rhs : lhs;
-    auto elem_size = b_.getInt64(ptr.GetPointeeTy()->GetSize());
+
+    if (other_ty.GetSize() != 8)
```
Comment (BurntBrunch) [inline src/ast/passes/codegen_llvm.cpp:1542]: Semantic analysis made sure this is a pointer or an int. So here we're encoding that pointer size == int64_t size == 8. While this is correct, I think it would be more obvious with an explicit integer check on other_ty as well, so it doesn't look like we may zext pointers.

**Review by BurntBrunch — APPROVED** [review]
This is all pointer math on bpf-side pointers, so I don't _think_ it matters for 32-bit but maybe double check?

**Comment by viktormalik** [comment]
> This is all pointer math on bpf-side pointers, so I don't _think_ it matters for 32-bit but maybe double check?

That's correct, the verifier prohibits 32-bit pointer arithmetic.

File: src/ast/passes/codegen_llvm.cpp (hunk 1 above)
Comment (viktormalik) [reply src/ast/passes/codegen_llvm.cpp]: Good point, added an int check.
