### PR TITLE
Simplify and fix probe index assignment

### LINKED ISSUE #2447: Can't attach multiple kprobes to multiple function
### What reproduces the bug?
Attach multi-attachment to **TWO** functions.

```bt
kprobe:generic_file_read_iter,
kprobe:filemap_fault
{
    printf("fst attachment on %s\n", func);
}

kprobe:generic_file_read_iter
{
    printf("snd attachment on %s\n", func);
}

kprobe:filemap_fault
{
    printf("snd attachment on %s\n", func);
}
```

The output dumped the following.

```
Attaching 4 probes...
snd attachment on generic_file_read_iter
snd attachment on filemap_fault
...
```

**fst statements are missing.**

#### Also describe what you expect to happen.

The output should dump the following.
```
Attaching 4 probes...
fst attachment on generic_file_read_iter
snd attachment on generic_file_read_iter
fst attachment on filemap_fault
snd attachment on filemap_fault
...
```

Besides, I've tried attach multi-attachment to **ONE** function.

```
kprobe:filemap_fault
{
    printf("fst attachment on %s\n", func);
}

kprobe:filemap_fault
{
    printf("snd attachment on %s\n", func);
}
```

And it works as expected.

```
Attaching 2 probes...
fst attachment on filemap_fault
snd attachment on filemap_fault
```

### bpftrace --info

`bpftrace v0.16.0-97-g50565`

### PR DESCRIPTION
**Pull request by lenticularis39**
Assign a unique index for each probe or attach point in generateProbe (the latter if expansion field is set to true). A new index is generated per each call of generateProbe, unless the probe/attach point already has an index; in the case, the old index is kept and used for the section. (this case happens when a wildcard is expanded).

This makes sure that each section in the generated bytecode is uniquely paired to a pair of AST probe/attach point and the actual probe name, preventing the program being attached to a wrong probe.

Fixes #2447

See the included test for a more minimal example of the issue. 

##### Checklist

- [x] Language changes are updated in `man/adoc/bpftrace.adoc` and if needed in `docs/reference_guide.md`
- [x] User-visible and non-trivial changes updated in `CHANGELOG.md`
- [x] The new behaviour is covered by tests

### CODE REVIEW

File: src/bpftrace.cpp [hunk 1]
```diff
@@ -282,8 +282,8 @@ int BPFtrace::add_probe(ast::Probe &p)
         {
           Probe probe_copy = probe;
           probe_copy.usdt_location_idx = i;
-          probe_copy.index = attach_point->index(func + "_loc" +
-                                                 std::to_string(i));
+          probe_copy.index = attach_point->index() > 0 ? attach_point->index()
+                                                       : p.index();
```
Comment (viktormalik) [inline src/bpftrace.cpp:286]: Shouldn't this assign different indices to different locations?

File: tests/runtime/probe [hunk 2]
```diff
@@ -30,6 +30,13 @@ EXPECT SUCCESS [0-9][0-9]*
 TIMEOUT 5
 AFTER ./testprogs/syscall read
 
+# https://github.com/iovisor/bpftrace/issues/2447
+NAME kfunc_multiple_attach_point_multiple_functions
+PROG BEGIN { @a = 2; @b = 1; @c = 1 } i:s:1 { exit() } kfunc:vfs_read, kfunc:vfs_open /@a != 0/ { @a -= 1 } kfunc:vfs_read /@b == 1/ { @b = 0 } kfunc:vfs_open /@c == 1/ { @c = 0 }
+EXPECT @a: 0\n@b: 0\n@c: 0
+TIMEOUT 5
```
Comment (viktormalik) [inline tests/runtime/probe:37]:
```suggestion
TIMEOUT 5
REQUIRES_FEATURE btf
```

File: tests/runtime/probe [hunk 3]
```diff
@@ -30,6 +30,13 @@ EXPECT SUCCESS [0-9][0-9]*
...
+AFTER ./testprogs/syscall read
```
Comment (viktormalik) [inline tests/runtime/probe:38]: We should probably add a comment that this also opens the file which calls `vfs_open`.

File: src/bpftrace.cpp (hunk 1 above)
Comment (lenticularis39) [reply src/bpftrace.cpp:286]: The sections generated for the USDT probe clone are distinguished by name, see this passage in `CodegenLLVM::visit(Probe &probe)`:
```cpp
          current_usdt_location_index_ = 0;
          for (int i = 0; i < attach_point->usdt.num_locations; ++i)
          {
            reset_ids();

            std::string full_func_id = match + "_loc" + std::to_string(i);
            generateProbe(probe, full_func_id, probefull_, func_type, true, i);
            current_usdt_location_index_++;
          }
```
Therefore, they don't need different indices (also they can't have different indices, otherwise they wouldn't be properly matched to the section, which has the attach point index common to the clone and the original program).  Actually, the previous implementation assignes indices unique in the context of a probe name (it was made to fix an issue with multiple identical probes, see #100), hence its index is even less unique globally.

File: tests/runtime/probe (hunk 2 above)
Comment (lenticularis39) [reply tests/runtime/probe:37]: I wonder why the other test cases (e.g. the one I copied mine from) don't have this, I thought kfunc usually (always?) require BTF?

Comment (viktormalik) [reply tests/runtime/probe:37]: It does, if some test is using kfuncs and missing the BTF requirement, it's a mistake.

**Comment by viktormalik** [comment]
Needs rebase to master to fix the CI.

File: src/bpftrace.cpp (hunk 1 above)
Comment (viktormalik) [reply src/bpftrace.cpp:286]: Thanks, that makes sense.

**Comment by lenticularis39** [comment]
I know, I am struggling a little with getting bpftrace to build with LLVM 12 to fix the codegen tests, CMake can be a pain sometimes :D

**Review by viktormalik — APPROVED** [review]
