### PR TITLE
maps: fix map checks for `print` and other cases (e.g. `zero`)

### LINKED ISSUE #4334: Crash when printing undefined map
Repro:
```
# bpftrace -e 'BEGIN { print(@asdf) }'
BUG: [/home/ajor/src/bpftrace/src/ast/dibuilderbpf.cpp:298] Cannot generate debug info for type none (0 is not a valid type size)
Aborted
```

What I expect:
```
# bpftrace -e 'BEGIN { print(@asdf) }'
stdin:1:9-20: ERROR: Undefined map: @asdf
BEGIN { print(@asdf) }
        ~~~~~~~~~~~
```

Bisected cause to this commit introducing map desugaring: 5349b3887b2fd8a1d966e3e3ead35ee0887e14ae @amscanne

### PR DESCRIPTION
**Pull request by amscanne**
Fixes #4334

##### Checklist

- ~[ ] Language changes are updated in `man/adoc/bpftrace.adoc`~
- ~[ ] User-visible and non-trivial changes updated in `CHANGELOG.md`~
- [x] The new behaviour is covered by tests

### CODE REVIEW

**Review by jordalgo — APPROVED** [review]

File: src/ast/passes/semantic_analyser.cpp [hunk 1]
```diff
@@ -3742,13 +3748,16 @@ bool SemanticAnalyser::check_arg(const Call &call,
 
 bool SemanticAnalyser::check_arg(const Call &call,
                                  size_t index,
-                                 [[maybe_unused]] const map_type_spec &spec)
+                                 const map_type_spec &spec)
```
Comment (viktormalik) [inline src/ast/passes/semantic_analyser.cpp:3751]: Is this just a drive-by change?

**Review by viktormalik — APPROVED** [review]
I would love to see at least *some* commit message saying what is being fixed and why.\\

Otherwise LGTM.

File: src/ast/passes/semantic_analyser.cpp (hunk 1 above)
Comment (amscanne) [reply src/ast/passes/semantic_analyser.cpp:3751]: Ah, the spec is being used so I just figured I would fix this because I was modifying this function. I can split it off, but it's not completely unrelated :)

**Comment by amscanne** [comment]
The commit message has been expanded & fixed.
